### ISSUE TITLE
can't update since in v3

### ISSUE THREAD

**Issue by isAAAc** [YunoHost/issues#1155]
Hi all, 
i just migrate to v3, 
but now i can't update/upgrade anymore : 

```
yunohost tools update
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 213, in <module>
    timeout=opts.timeout,
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 136, in cli
    moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 390, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 498, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/tools.py", line 428, in tools_update
    if not cache.update():
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 464, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: E:The repository 'https://packages.icinga.com/debian icinga-stretch Release' does not have a Release file., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'https://download.docker.com/linux/debian stretch Release' does no longer have a Release file., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'https://deb.nodesource.com/node_6.x stretch Release' does no longer have a Release file., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 Release: Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 68818C72E52529D4, E:The repository 'http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 Release' is not signed.
```

thx for your help ;)

**Comment by alexAubin** [comment]
>E:The repository 'https://packages.icinga.com/debian icinga-stretch Release' does not have a Release file.
>E:The repository 'https://download.docker.com/linux/debian stretch Release' does no longer have a Release file.
>E:The repository 'https://deb.nodesource.com/node_6.x stretch Release' does no longer have a Release file.
>E:The repository 'http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 Release' is not signed.

Hmmm it looks like all those repo are problematic ? Not sure why so many of them ... But that doesn't surprise me either too much ? I don't know how much of a good idea this is, but naively you could try commenting those out in the sources.list files ...

**Comment by isAAAc** [comment]
yep you're true, i saw that too, 
i just removed icinga2 (an old useless install, and just removed the repo too)
but i don't know why the other are there, probably added for some ynh apps, so i don't know if it's a good idea to comment them
?

**Comment by isAAAc** [comment]
apt-get update tells me : 
```
E: The repository 'https://download.docker.com/linux/debian stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://deb.nodesource.com/node_6.x stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Erreur de GPG : http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 Release : Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 68818C72E52529D4
W: The repository 'http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Comment by isAAAc** [comment]
more docker.list 
`deb [arch=amd64] https://download.docker.com/linux/debian stretch edg`

more mongodb-org-3.2.list 
`deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main`

more nodesource.list 
```
deb https://deb.nodesource.com/node_6.x stretch main
deb-src https://deb.nodesource.com/node_6.x stretch main
```

**Comment by isAAAc** [comment]
> Have you added those repos by yourself?

yes for incinga2 (removed)
but i'm not shure for the others, i tested so many stuff on this server :/
nodesource perhaps for etherpad or peertube or friendica (?) , a paquet wich needed nodejs i suppose, i had trouble with it one moment ago, 
for mongodb and docker, i really don't know , i try to move them otherelse to test if things are better

**Comment by Psycojoker** [comment]
For nodejs I don't think so since we are using nvm (or maybe a very old unofficial app)

Could you list all the app you have installed? To see if we need to fix some apps

**Comment by isAAAc** [comment]
ok it works really better with only gandi and yunohost repos, 
yunohost tools update && yunohost tools upgrade && yunohost app upgrade works (trouble with jirafeau, but it's an other trouble)

how could i know what using the moved repos ? 
do you think i should just wait like that , apps wich need missing repos will cry one moment or one other ?

**Comment by isAAAc** [comment]
extract from yunohost tools diagnosis : 
```
services: 
  avahi-daemon: running (enabled)
  dnsmasq: running (enabled)
  docker: failed (enabled)
  dovecot: running (enabled)
  etherpad_mypads: running (enabled)
  fail2ban: running (enabled)
  glances: running (enabled)
  mattermost: running (enabled)
  metronome: running (enabled)
  mongod: dead (not-found)
  mumble-server: unknown (unknown)
  mysql: running (enabled)
  nginx: running (enabled)
  nslcd: running (enabled)
  php7.0-fpm: running (enabled)
  postfix: exited (enabled)
  redis-server: running (enabled)
  rspamd: running (enabled)
  slapd: running (enabled)
  ssh: running (enabled)
  togetherjs: running (enabled)
  uwsgi: running (enabled)
  yunohost-api: running (enabled)
  yunohost-firewall: exited (enabled)

applications: 
  dokuwiki: Dokuwiki
  etherpad_mypads: Etherpad Mypads
  framaestro: Framaestro
  framaestro_hub: Framaestro hub
  garradin: Garradin
  jirafeau: Jirafeau
  kanboard: Kanboard
  mattermost: Mattermost
  my_webapp: AirTime
  nextcloud: Nextcloud
  opensondage: OpenSondage
  peertube: PeerTube
  phpldapadmin: phpLDAPadmin
  phpmyadmin: phpMyAdmin
  roundcube: Roundcube
  searx: Searx
  wallabag2: Wallabag
  wemawema: WemaWema
  wordpress__2: WordPress
  wordpress__3: WordPress
  zerobin: Zerobin
```
yunohost app map
```
krashboyz.org/blog: WordPress
krashboyz.org/date/: OpenSondage
krashboyz.org/dokuwiki/: Dokuwiki
krashboyz.org/garradin: Garradin
krashboyz.org/jirafeau/: Jirafeau
krashboyz.org/kanboard/: Kanboard
krashboyz.org/maestro/: Framaestro
krashboyz.org/nextcloud: Nextcloud
krashboyz.org/pad: Etherpad Mypads
krashboyz.org/phpldapadmin/: phpLDAPadmin
krashboyz.org/phpmyadmin: phpMyAdmin
krashboyz.org/wallabag2/: Wallabag
krashboyz.org/webmail/: Roundcube
krashboyz.org/wemawema: WemaWema
krashboyz.org/zerobin/: Zerobin
maestro.krashboyz.org/: Framaestro hub
mat.krashboyz.org/: Mattermost
media.krashboyz.org/: PeerTube
port.krashboyz.org/blog: WordPress
searx.krashboyz.org/: Searx
stream.krashboyz.org/airtime: AirTime
```

**Comment by Psycojoker** [comment]
Apps aren't supposed to used those depos iirc (or at least backports) so that might be on your side or badly made apps, but we would need to investigate :/

**Comment by isAAAc** [comment]
i think the docker service is useless on my server, i perhaps tried the docker stuff long time ago and the uninstall didn't removed it cleanly

yes, if you can help me to clean all this , it could be great ;)

**Comment by Psycojoker** [comment]
iirc it's solved now
