### ISSUE TITLE
"YunoHost a rencontré une erreur interne :/"

### ISSUE THREAD

**Issue by Suniron** [YunoHost/issues#1171]
**Action**
```
GET /diagnosis
 {"locale":"fr"}
```

**Trace**
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 406, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 498, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/tools.py", line 566, in tools_diagnosis
    diagnosis['packages'] = ynh_packages_version()
  File "/usr/lib/moulinette/yunohost/utils/packages.py", line 465, in ynh_packages_version
    with_repo=True
  File "/usr/lib/moulinette/yunohost/utils/packages.py", line 404, in get_installed_version
    cache = apt.Cache()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 113, in __init__
    self.open(progress)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 164, in open
    self._cache = apt_pkg.Cache(progress)
Error: E:Write error - write (28: No space left on device), E:IO Error saving source cache, E:The package lists or status file could not be parsed or opened.
```

**Comment by M5oul** [comment]
The logs says it all: `No space left on device`.

You should free space.
