### ISSUE TITLE
Random wtf error in webadmin : Unable to run gpg - it may not be available.

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1326]
Playing with a new instance, being logged in the admin ... I already created a user and installed Nextcloud, everything went ~smoothly.

Then did nothing in particular, but suddenly I try to go to "Applications" to install another app, and I get an ugly traceback : 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 473, in process
    arguments = vars(self.parser.parse_args(args, **kwargs))
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 653, in parse_args
    auth = msignals.authenticate(klass(), **auth_conf)
  File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 279, in authenticate
    return self._authenticate(authenticator, help)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 483, in _do_authenticate
    return authenticator(token=(s_id, s_hash))
  File "/usr/lib/python2.7/dist-packages/moulinette/authenticators/__init__.py", line 106, in __call__
    password = self._retrieve_session(s_id, s_hash)
  File "/usr/lib/python2.7/dist-packages/moulinette/authenticators/__init__.py", line 157, in _retrieve_session
    gpg = gnupg.GPG()
  File "/usr/lib/python2.7/dist-packages/gnupg.py", line 755, in __init__
    raise OSError(msg)
OSError: Unable to run gpg - it may not be available.
```

**Comment by dosch** [comment]
I have the same issue suddenly.

Action
```

GET /apps
{"locale":"en","installed":""}
```

Traceback
```

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 473, in process
    arguments = vars(self.parser.parse_args(args, **kwargs))
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 653, in parse_args
    auth = msignals.authenticate(klass(), **auth_conf)
  File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 279, in authenticate
    return self._authenticate(authenticator, help)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 483, in _do_authenticate
    return authenticator(token=(s_id, s_hash))
  File "/usr/lib/python2.7/dist-packages/moulinette/authenticators/__init__.py", line 106, in __call__
    password = self._retrieve_session(s_id, s_hash)
  File "/usr/lib/python2.7/dist-packages/moulinette/authenticators/__init__.py", line 157, in _retrieve_session
    gpg = gnupg.GPG()
  File "/usr/lib/python2.7/dist-packages/gnupg.py", line 755, in __init__
    raise OSError(msg)
OSError: Unable to run gpg - it may not be available.
```

**Comment by alexAubin** [comment]
All computers are broken :|

**Comment by dosch** [comment]
> All computers are broken :|

Are you stating a fact, or merely having an existential crisis?

**Comment by alexAubin** [comment]
Both @.@

**Comment by DmitryStrunevsky** [comment]
`sudo apt install gnupg2` 

This command solved this problem for me.

**Comment by Psycojoker** [comment]
I really wonder if those apps aren't removing gnupg2 on uninstall? It's always after an app removal that we observe that :/ 

Maybe this dependencies is not strong enough and we should also enforce gnupg2 https://github.com/YunoHost/moulinette/blob/stretch-unstable/debian/control#L16 ?

**Comment by alexAubin** [comment]
Indeed ... I'm able to `apt remove gnupg2` and no other package seems to require it ... But as far as I thought, I think I saw `python-gnupg` explicitly calling `gpg` in its code so it shoud really have `gnupg(2)` as a dependency >.>

**Comment by Psycojoker** [comment]
Turned out it's "gnupg1" on which we depends, not "gnupg2" https://packages.debian.org/stretch/python-gnupg

**Comment by alexAubin** [comment]
This seem to happens more and more for some reason ...

**Comment by Psycojoker** [comment]
Everytime it happens it was after some app removal (mastodon I think for the last one I have in mind).

Also it's not really useful anymore to do that thing with gpg (I'm not even convinced it's really secure), I've tried to remove it from the code but I've failed to do that on the admin part (on the cli it's fine), it's really a very easy to handle part of the code :/

**Comment by alexAubin** [comment]
Indirectly fixed in https://github.com/YunoHost/moulinette/pull/216
