### ISSUE TITLE
YunoHost a rencontré une erreur interne :/

### ISSUE THREAD

**Issue by ghost** [YunoHost/issues#1380]
Action
GET /logs
 {"locale":"fr","with_details":"","limit":"25"}
Trace
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 111, in log_list
    entry["success"] = metadata.get("success", "?") if metadata else "?"
UnboundLocalError: local variable 'metadata' referenced before assignment

**Comment by ghost** [comment]
Le fichier yaml de metadata associé aux logs est corrompu : '{md_file}'

**Comment by alexAubin** [comment]
Le problème devrait être corrigé dans les nouvelles versions
