### ISSUE TITLE
manifest.json: UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by decentral1se** [YunoHost/issues#1398]
```
            {
                "name": "currency_symbol",
                "type": "string",
                "ask": {
                    "en": "Currency symbol of the cooperative"
                },
                "default": "€",
                "example": "€"
            },
```

> €

```
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 214, in <module>
    timeout=opts.timeout,
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 136, in cli
    moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 425, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 282, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/app.py", line 801, in app_install
    args_odict = _parse_args_from_manifest(manifest, 'install', args=args_dict)
  File "/usr/lib/moulinette/yunohost/app.py", line 2367, in _parse_args_from_manifest
    return _parse_args_in_yunohost_format(args, action_args)
  File "/usr/lib/moulinette/yunohost/app.py", line 2438, in _parse_args_in_yunohost_format
    ask_string += ' (default: {0})'.format(arg_default)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 0: ordinal not in range(128)
```

I tried a bunch of tricks I can remember but didn't have any luck. I could get the error to go from `/usr/lib/moulinette/yunohost/app.py` down into ` /usr/lib/python2.7/dist-packages/moulinette/core.py` on a locale lookup but py2 unicode mishandling has defeated my patience again.

So, now I created an issue. It's all our problem :bomb:

**Comment by alexAubin** [comment]
Closing because issue is 3 years old and may have been fixed since then while moving to Python 3 and other refactorings
