### ISSUE TITLE
Hotspot badly installed

### ISSUE THREAD

**Issue by harpogit** [YunoHost/issues#1473]
Hello everybody,
Trying an update, i've got an issue through the web interface of YNH. Here is the message :

` YunoHost a rencontré une erreur interne :/
Vraiment navré.
Vous devriez chercher de l’aide sur le forum ou le salon pour résoudre le problème, ou rapporter le bogue sur l’outil de suivi.
Les informations suivantes peuvent être utile à l’interlocuteur vous aidant :
Action `

` PUT /update
 {"locale":"fr"} ` 

` Trace `

` Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/tools.py", line 521, in tools_update
    upgradable_apps = list(_list_upgradable_apps())
  File "/usr/lib/moulinette/yunohost/tools.py", line 549, in _list_upgradable_apps
    'label': app_dict['settings']['label'],
KeyError: 'label' `

` hotspot semble être mal installé `

I tried to de-install ynh-hotspop by sso to re-install it properly :

`# yunohost app remove hotspot`

Then I tried to reinstall : 

` # yunohost app install hotspot ` but ... https://paste.yunohost.org/raw/xenofovume

What is it about? I don't understand. Thank you for your help.

**Comment by harpogit** [comment]
Hi Alexandre,

I didn't dare to do it first. So I used # mv /var/www/hotspot
/var/www/oldhotspot before re-install.

It seems to be running now. Nevertheless I don't understand why the
upgrade seems to have caused the bad comportment.

Thanks a lot !

;-)
||||

||
||

||||
