### ISSUE TITLE
LetsEncrypt certificate creation fails on IPv6-only server

### ISSUE THREAD

**Issue by treysis** [YunoHost/issues#1506]
I have an IPv6-only vserver, that has no IPv4-connectivity at all. The cert-install script tries to connect to "https://ip.yunohost.org" for whatever reason, which of course fails because there is no IPv4-connectivity. Why doesn't it use ip6.yunohost.org as fallback? It shouldn't rely on IPv4-connectivity:

```
35577 INFO Now attempting install of certificate for domain yunohost.mydomain.tld!
35578 DEBUG Starting new HTTPS connection (1): ip.yunohost.org
35579 DEBUG Could not get public IPv4 : Invalid url https://ip.yunohost.org (does this site exists?)
95581 DEBUG action [21717.1] executed in 95.378s
95582 DEBUG lock has been released
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 214, in <module>
    timeout=opts.timeout,
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 136, in cli
    moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 425, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/domain.py", line 237, in domain_cert_install
    return yunohost.certificate.certificate_install(domain_list, force, no_checks, self_signed, staging)
  File "/usr/lib/moulinette/yunohost/certificate.py", line 145, in certificate_install
    domain_list, force, no_checks, staging)
  File "/usr/lib/moulinette/yunohost/certificate.py", line 297, in _certificate_install_letsencrypt
    _display_debug_information(domain)
  File "/usr/lib/moulinette/yunohost/certificate.py", line 882, in _display_debug_information
    dns_ip = _get_dns_ip(domain)
  File "/usr/lib/moulinette/yunohost/certificate.py", line 845, in _get_dns_ip
    answers = resolver.query(domain, "A")
  File "/usr/lib/python2.7/dist-packages/dns/resolver.py", line 949, in query
    timeout = self._compute_timeout(start)
  File "/usr/lib/python2.7/dist-packages/dns/resolver.py", line 858, in _compute_timeout
    raise Timeout(timeout=duration)
dns.exception.Timeout: The DNS operation timed out after 30.0009040833 seconds
```

**Comment by M5oul** [comment]
Hi, thanks for the report.
This is a known issue since LE integration into YunoHost: #769.

**Comment by alexAubin** [comment]
Should be fixed from a while ago, and anyway there are plenty of issues to be expected on IPv6-only servers
