### ISSUE TITLE
Corrupt .gz archives (because 'CRC check failed') breaks backup features

### ISSUE THREAD

**Issue by LeoBoudet** [YunoHost/issues#1521]
Ce n'est pas la première fois que j'ai ce problème, ça s'accompagne en général de l'impossibilité de faire des sauvegardes complètes à la moulinette.
Si je veux ensuite accéder à mes fichiers de sauvegardes par l'interface web, je me retrouve avec le message : "YunoHost a rencontré une erreur interne :/" et les infos suivantes :

### Action
```
GET /backup/archives
 {"locale":"fr","with_info":""}
```
### Trace
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/backup.py", line 2201, in backup_list
    d[a] = backup_info(a, human_readable=human_readable)
  File "/usr/lib/moulinette/yunohost/backup.py", line 2241, in backup_info
    if "info.json" in tar.getnames():
  File "/usr/lib/python2.7/tarfile.py", line 1846, in getnames
    return [tarinfo.name for tarinfo in self.getmembers()]
  File "/usr/lib/python2.7/tarfile.py", line 1838, in getmembers
    self._load()        # all members, we first have to
  File "/usr/lib/python2.7/tarfile.py", line 2419, in _load
    tarinfo = self.next()
  File "/usr/lib/python2.7/tarfile.py", line 2350, in next
    self.fileobj.seek(self.offset - 1)
  File "/usr/lib/python2.7/gzip.py", line 443, in seek
    self.read(1024)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x4e72dad1 != 0x7c0f3b23L
```
En espérant que cela puisse être utile.

Léo

**Comment by Thovi98** [comment]
J’ai exactement le même problème. 

**Action** 
```

GET /backup/archives
 {"locale":"fr","with_info":""}
```

**Trace**
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 439, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 523, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/backup.py", line 2201, in backup_list
    d[a] = backup_info(a, human_readable=human_readable)
  File "/usr/lib/moulinette/yunohost/backup.py", line 2241, in backup_info
    if "info.json" in tar.getnames():
  File "/usr/lib/python2.7/tarfile.py", line 1846, in getnames
    return [tarinfo.name for tarinfo in self.getmembers()]
  File "/usr/lib/python2.7/tarfile.py", line 1838, in getmembers
    self._load()        # all members, we first have to
  File "/usr/lib/python2.7/tarfile.py", line 2419, in _load
    tarinfo = self.next()
  File "/usr/lib/python2.7/tarfile.py", line 2350, in next
    self.fileobj.seek(self.offset - 1)
  File "/usr/lib/python2.7/gzip.py", line 443, in seek
    self.read(1024)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xe9928d8a != 0x1cad0877L
```

**Comment by alexAubin** [comment]
(As discussed in other places, my opinion on this topic is that we should just stop compressing archives by default. I doubt there are many use-case where compressing the archive is really worth it. Either the archive is small and it doesn't matter so much, or it's large and usually made of already-compressed data like images or videos. In that case, trying to compress 50GB+ of already-compressed data is just a huge waste of time and CPU)

**Comment by alexAubin** [comment]
A partial fix is on the way to avoid miserably crashing when listing archives if just one archive is corrupted...

On the other hand, I don't know what to do about this CRC check. It just looks like the file is corrupted and can't be untarred ... Can any body of you elaborate on the context ? Did you copy the archive from / to another device when this happened? Could it be that the copy was interrupted ? How did you proceed ?

**Comment by Thovi98** [comment]
I don't remember the specific context, but I can say that I didn't do something special... I don't think that I interrupted the processus...

**Comment by Jaxom99** [comment]
Okay, I have the same trouble (see https://github.com/YunoHost/issues/issues/1641) on a freshly installed/restored server.
I indeed copied backup files with scp, and I see the warnings now that I look for them :
> Warning: It looks like the backup archive '/home/yunohost.backup/archives/auto-2020-07-05-apps.tar.gz' is corrupted : CRC check failed 0xc8081e72 != 0x13b82baL 

It only displays for backups including `--apps someapps*`, and not for my backup with only ` --apps nextcloud` where I set BACKUP_CORE_ONLY=1. M

aybe it comes from the backup script of one of the other apps I have ? @thovi98 @leoboudet what apps did you backup in the corrupted files ?

I guess the temporary fix is just to remove the files from `archives` directory and store them elsewhere ?

**Comment by LeoBoudet** [comment]
For my part, it was a backport problem. After a clean install of Yunohost, even with more apps and bigger files, everything works fine as long as I am patient enough.

> aybe it comes from the backup script of one of the other apps I have ? @Thovi98 @LeoBoudet what apps did you backup in the corrupted files ?

Not my case since a new install solved the problem but just for information: Wordpress, Nextcloud, Gitea, Etherpad, Redirect, Peertube, Rainloop, SOGo, Webapp, Discourse.

> I guess the temporary fix is just to remove the files from `archives` directory and store them elsewhere ?

I'd say yes. On my previous server, I used to delete the corrupted files to make situation better, until it broke again.

**Comment by Thovi98** [comment]
I don’t remember exactly what made it corrupt, but it was related with a backup with Nextcloud as long as I remember. I just deleted the corrupted file and have never seen this issue again.

**Comment by zamentur** [comment]
New backup are not compressed, so i close this issue
