### ISSUE TITLE
Yunohost backup fails because of some files in the home folder

### ISSUE THREAD

**Issue by farvardin** [YunoHost/issues#1570]
I make some automatic backup from the crontable. It worked until last week.

I discovered it failed only because of some date in the /home folder (using `sudo yunohost backup create --system data_home`)

I remembered then I've checked out a git repository the day before the backup began to fail. There is nothing special in this repository, some pdf, some yaml, md, java and images files... Some files with accented letters, maybe some with long file name, I don't know. `tar cfvz` works perfectly on this subfolder. I suppose there is a problem with the python implementation of tar (`/usr/lib/python2.7/tarfile.py`).

If I remove the git repository, the backup is working again.

How could I help to trace the problem (this git repo is private, it's not accessible)?

> Info: Collecting files to be backed up for the app 'roundcube'…
> Info: [+++.................] > Loading installation settings...
> Info: [###+++..............] > Backing up the main app directory...
> Info: [######++++..........] > Backing up nginx web server configuration...
> Info: [##########+++.......] > Backing up php-fpm configuration...
> Info: [#############+++....] > Backing up the MySQL database...
> Info: Creating a backup archive from the collected files…
> Traceback (most recent call last):
>   File "/usr/bin/yunohost", line 218, in <module>
>     timeout=opts.timeout,
>   File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 135, in cli
>     moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
>   File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 425, in run
>     ret = self.actionsmap.process(args, timeout=timeout)
>   File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 527, in process
>     return func(**arguments)
>   File "/usr/lib/moulinette/yunohost/backup.py", line 2178, in backup_create
>     backup_manager.backup()
>   File "/usr/lib/moulinette/yunohost/backup.py", line 754, in backup
>     method.mount_and_backup(self)
>   File "/usr/lib/moulinette/yunohost/backup.py", line 1591, in mount_and_backup
>     self.backup()
>   File "/usr/lib/moulinette/yunohost/backup.py", line 1892, in backup
>     tar.add(path['source'], arcname=path['dest'])
>   File "/usr/lib/python2.7/tarfile.py", line 2032, in add
>     recursive, exclude, filter)
>   File "/usr/lib/python2.7/tarfile.py", line 2032, in add
>     recursive, exclude, filter)
>   File "/usr/lib/python2.7/tarfile.py", line 2032, in add
>     recursive, exclude, filter)
>   File "/usr/lib/python2.7/tarfile.py", line 2032, in add
>     recursive, exclude, filter)
>   File "/usr/lib/python2.7/tarfile.py", line 2028, in add
>     self.addfile(tarinfo)
>   File "/usr/lib/python2.7/tarfile.py", line 2048, in addfile
>     buf = tarinfo.tobuf(self.format, self.encoding, self.errors)
>   File "/usr/lib/python2.7/tarfile.py", line 1008, in tobuf
>     return self.create_gnu_header(info)
>   File "/usr/lib/python2.7/tarfile.py", line 1039, in create_gnu_header
>     return buf + self._create_header(info, GNU_FORMAT)
>   File "/usr/lib/python2.7/tarfile.py", line 1124, in _create_header
>     itn(info.get("mtime", 0), 12, format),
>   File "/usr/lib/python2.7/tarfile.py", line 221, in itn
>     s = chr(n & 0377) + s
> TypeError: unsupported operand type(s) for &: 'float' and 'int'
> 

I've already talked about this on the forum: https://forum.yunohost.org/t/yunohost-backup-via-fail-since-3-7-1/10890/14?u=farvardin

**Comment by alexAubin** [comment]
Hey there,

randomly passing by .. It's indeed tricky to debug and really seems to happen in the tar lib ...

Depending on how comfortable you are with tweaking stuff, naively I would try to 
- open `/usr/lib/python2.7/tarfile.py`, 
- go to line 1124 in _create_header, 
- and before `itn(info.get("mtime", 0), 12, format)` try to print the value of `info` or `info.get("mtime", 0)` since that's what seems to be related to the issue ... (more specifically inside itn later)

**Comment by farvardin** [comment]
(I've found the final reason of the error, at the end of this message)

I've seen it's crashing before starting to actually compress the files.

I've managed to copy the /usr/lib/python2.7/tarfile.py in a temp folder (and call it tarfile2.py) and make some tests. I've created a python script to compress a test folder:

```
import tarfile2

tar = tarfile2.open("TarName.tar.gz", "w:gz")
tar.add("test", arcname="TarName")
tar.getnames()
tar.list(verbose=True)
tar.close()
```

I've added a "print info" after the def close to the line 1124. Now when I run the script I get a list of files before the crash:

> {'uid': 1007, 'chksum': 0, 'uname': 'admin', 'gname': '', 'magic': 'ustar  \x00', 'size': 84, 'devmajor': 0, 'name': 'TarName/services/site/archetypes/default.md', 'devminor': 0, 'gid': 1007, 'mtime': 1586868141.0, 'mode': 420, 'linkname': '', 'type': '0'}
> {'uid': 1007, 'chksum': 0, 'uname': 'admin', 'gname': '', 'magic': 'ustar  \x00', 'size': 0L, 'devmajor': 0, 'name': 'TarName/services/site/public/', 'devminor': 0, 'gid': 1007, 'mtime': 10384504605.0, 'mode': 493, 'linkname': '', 'type': '5'}
> Traceback (most recent call last): (same as above)


I could narrow the problem to a static site generated by hugo. If I ran the previous python script only on this folder, it crashed. 

Then I noticed the generated folder, called "public", had a wrong date:

> drwxr-xr-x  11 admin 1007 4.0K Jan 27  2299 public

If I copy it without preserving the timestamp, it no longer crashes /usr/lib/python2.7/tarfile.py !

I tried again to run the hugo script, then the date was different:

> drwxr-xr-x  2 admin root 4.0K Apr 22 08:02 i18n
> drwxr-xr-x 11 admin root 4.0K Aug 30  1754 public
> -rw-r--r--  1 admin root   83 Apr 22 08:02 README.md

1754 is not correct, but it doesn't crash tarfile.py at least!
I don't understand why the date was 2299 in my case.

It's a know issue of hugo:
https://github.com/gohugoio/hugo/issues/6161

So for now we have at least 2 bugs: 
- one in hugo
- one in tarfile.py (it should crash for this reason, even if the date is ahead in time), I don't know if it's fixed in the python 3 version. The unix tar command doesn't crash in this case.

Can we consider it's not very safe for the yunohost backup script to use tarfile.py which is not always reliable?  It might be possible to use the venerable tar instead...
It's up to you to decide now ;)

**Comment by zamentur** [comment]
Seems a very specific issue (date to 2299...).

We plan to use a local borg repository as default method for backup, so i guess this bug will be less important.

However, we could indeed use (carefully) the venerable tar with something like `tar --append --file=archive.tar /home`, we should be careful about injection.
