### ISSUE TITLE
Moulinette lock disappeared after huge backup creation

### ISSUE THREAD

**Issue by tompatulpan** [YunoHost/issues#1631]
Hi,
when doing backup within Yunohost and Seafile (approx. 200GB) Iv got errors according to below.
I don't get this errors if I exclude Sefile to backup (5GB).
First reported here - https://github.com/YunoHost-Apps/seafile_ynh/issues/61

```
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 218, in <module>
    timeout=opts.timeout,
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 150, in cli
    moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 469, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 591, in process
    logger.debug("action [%s] executed in %.3fs", log_id, stop - start)
  File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 598, in __exit__
    self.release()
  File "/usr/lib/python2.7/dist-packages/moulinette/core.py", line 544, in release
    os.unlink(self._lockfile)
OSError: [Errno 2] No such file or directory: '/var/run/moulinette_yunohost.lock'
```

**Comment by Jaxom99** [comment]
Hi o/
I'm no expert, just passing by, but from your log, it seems that a general "timeout" is reached... I wonder if there is such a setting in core... If so, I guess you could change its value before starting your backup.

Other theory: another process grabs the lockfile, do you run any automatic script during your backup ?

(If you can provide more context: what is your hardware setup ? does the backup operation actually last for a while before getting this error ? And maybe a core maintaner could use your full log)

**Comment by alexAubin** [comment]
(Not sure how that happens, but I guess an easy fix is to add an `if os.exists(self._lockfile)` before that unlink ...)
