### ISSUE TITLE
TypeError stacktrace on cert renewal failure

### ISSUE THREAD

**Issue by JocelynDelalande** [YunoHost/issues#1678]
Today cert renewal failed on a yunohost server. There appears to be an error in the error handling itself :

```
/etc/cron.daily/yunohost-certificate-renew:
Now attempting renewing of certificate for domain www.example.net !
Parsing account key...
Parsing CSR...
Found domains: www.example.net
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying www.example.net...
Challenge did not pass for www.example.net: {u'status': u'invalid', u'challenges': [{u'status': u'invalid', u'validationRecord': [{u'url': u'http://www.example.net/.well-known/acme-challenge/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', u'hostname': u'www.example.net', u'addressUsed': u'X.X.X.X', u'port': u'80', u'addressesResolved': [u'X.X.X.X']}, {u'url': u'https://www.example.net/.well-known/acme-challenge/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', u'hostname': u'www.example.net', u'addressUsed': u'X.X.X.X', u'port': u'443', u'addressesResolved': [u'X.X.X.X']}], u'url': u'https://acme-v02.api.letsencrypt.org/acme/chall-v3/8519438149/Q5eVAQ', u'token': u'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', u'error': {u'status': 403, u'type': u'urn:ietf:params:acme:error:unauthorized', u'detail': u'Invalid response from https://www.example.net/.well-known/acme-challenge/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX [X.X.X.X]: "<html>\\r\\n<head><title>404 Not Found</title><script type=\\"text/javascript\\" src=\\"/ynh_portal.js\\"></script><link type=\\"text/css\\" rel"'}, u'type': u'http-01'}], u'identifier': {u'type': u'dns', u'value': u'www.example.net'}, u'expires': u'2020-11-18T05:26:54Z'}
Certificate renewing for www.example.net failed !
Please consider checking the 'DNS records' (basic) and 'Web' categories of the diagnosis to check for possible issues that may prevent installing a Let's Encrypt certificate on domain www.example.net.
L’opération 'Renouveler le certificat Let’s Encrypt de 'www.example.net'' a échoué ! Pour obtenir de l’aide, merci de partager le journal de l’opération en utilisant la commande 'yunohost log display 20201111-052639-letsencrypt_cert_renew-www.example.net --share'
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/certificate.py", line 388, in certificate_renew
    _fetch_and_enable_new_certificate(domain, staging, no_checks=no_checks)
  File "/usr/lib/moulinette/yunohost/certificate.py", line 535, in _fetch_and_enable_new_certificate
    raise YunohostError('certmanager_cert_signing_failed')
YunohostError: Impossible de signer le nouveau certificat

Impossible de signer le nouveau certificat
Sending email with details to root ...
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 218, in <module>
    timeout=opts.timeout,
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 149, in cli
    moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 469, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 588, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/domain.py", line 349, in domain_cert_renew
    return yunohost.certificate.certificate_renew(domain_list, force, no_checks, email, staging)
  File "/usr/lib/moulinette/yunohost/certificate.py", line 404, in certificate_renew
    _email_renewing_failed(domain, msg + "\n" + e, stack.getvalue())
TypeError: cannot concatenate 'str' and 'YunohostError' objects
run-parts: /etc/cron.daily/yunohost-certificate-renew exited with return code 1

```

package versions :
```
# dpkg -l|grep yunohost
ii  python-toml                           0.10.0-1+yunohost                                              all          library for Tom's Obvious, Minimal Language - Python 2.7
ii  yunohost                              4.0.8                                                          all          manageable and configured self-hosting server
ii  yunohost-admin                        4.0.4                                                          all          web administration interface for yunohost

```

That is the first time I see this error.

**Comment by alexAubin** [comment]
Fixed since then
