### ISSUE TITLE
Error 'getspnam(): name not found' at post-installation on DEBIAN 10

### ISSUE THREAD

**Issue by kalak-sudo** [YunoHost/issues#1686]
Hi!

I have tried 2 times with new DEBIAN 10 installations, and both times got the same error after entering the admin password on the post-install:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 489, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 588, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 313, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/tools.py", line 354, in tools_postinstall
    tools_adminpw(password, check_strength=not force_password)
  File "/usr/lib/moulinette/yunohost/tools.py", line 158, in tools_adminpw
    hash_root = spwd.getspnam("root").sp_pwd
KeyError: 'getspnam(): name not found'
```

What is wrong? 

Thanks in advanced!

**Comment by alexAubin** [comment]
Weeeeeeeell that would sound like the root user does not exists which is ... "concerning".

What's your exact setup ? Is it an ARM board ? A VPS bought online ...?

**Comment by kalak-sudo** [comment]
Is a VPS bough online with this:

Debian 10 64 bits. 
VCores: 0.5
RAM: 1 GB
SSD: 20GB

All new and empty. I have tried with "apt-get update && apt-get full-upgrade" before installing Yunohost, and the same error.

**Comment by alexAubin** [comment]
- How are you running the postinstall exactly (what command ... with or without sudo)
- Are you launching the postinstall from a root shell ? 
- Can you provide *the full log* and not just the Traceback

**Comment by kalak-sudo** [comment]
1.     How are you running the postinstall exactly (what command ... with or without sudo)
without sudo

2.     Are you launching the postinstall from a root shell ?
yes, from the same shell where I installed it (root shell)

3.     Can you provide the full log and not just the Traceback
Nope, I destroyed the instance some minutes ago. But probably, I am doing something wrong with the sudo. 

FYI, I get the same error doing it via web.

**Comment by alexAubin** [comment]
Zbleh...

If you want to pinpoint the issue, you can try the following tests : 

```
python -c "import spwd; spwd.getspnam('root')"
# ---> this should display *nothing* if you run the command as root (or with sudo)
# ---> if you run the command as a non-root user, you should see the 'KeyError: 'getspnam(): name not found'' message, which is expected
```

```
cat /etc/shadow | grep -q "^root:" && echo "yes root is in /etc/shadow"
# ---> this should display "yes root is in /etc/shadow" if you run the command as root (or with sudo)
```

**Comment by kalak-sudo** [comment]
I have tried it again, and before installing Yunohost, I have typed: as root

`root@SERVER:~# python -c "import spwd; spwd.getspnam('root')"`

And got:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'getspnam(): name not found'
```

And when I type:

`cat /etc/shadow | grep -q "^root:" && echo "yes root is in /etc/shadow"`

I get *nothing*.

What is happening? Or what I am doing wrong?

Thanks @alexAubin

**Comment by alexAubin** [comment]
I doubt *you* are doing something wrong ... it just looks like your VPS is a bit funky ... 

From what I understand, "root" is not in /etc/shadow (= the place where unix password hashes are stored) and that's a bit funky ... naively it might be because your root user has no password defined ? (Which hopefully doesn't mean that anybody can log in as root on your setup, but that *nobody* can log as root using passsword authentication ...)

Anyway - in fact that shouldn't be a big deal because Yunohost is not supposed to miserably fail ([it's wrapped in a try/except](https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/tools.py#L149-L160)) and I'm suspecting the real issue has nothing to do with this (and the fact that it displays the stacktrace for this is only because of some sort of "glitch" in the way python handles exceptions.. but that's really technical)

Anyway yeah, would definitely need to look at the full log of the postinstall to have a clearer idea of what's going on and what's the real issue here

**Comment by alexAubin** [comment]
Annnnnnnnnnd after clicking "Comment" I realize I'm completely misinsterpreting the try/except .. The except only catches the 'IOError' and not the 'KeyError' ...

So turns out this is indeed the real issue.

As a workaround I would : 

- define a dummy temporary password for root using the command: `passwd`
- after this, running the previous command should work : 

```
cat /etc/shadow | grep -q "^root:" && echo "yes root is in /etc/shadow"
```

- Annnnnd after this the postinstall should work...

**Comment by alexAubin** [comment]
This will be fixed in 4.1 with https://github.com/YunoHost/yunohost/commit/63166d05fad940db441edf922c4cfaf16120a643

**Comment by kalak-sudo** [comment]
I have created a new instance of Debian 10, and here is the command line:

```
root@SERVER:~# python -c "import spwd; spwd.getspnam('root')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'getspnam(): name not found'

root@yunosi:~# passwd
New password: 
Retype new password: 
passwd: password updated successfully

root@SERVER:~# python -c "import spwd; spwd.getspnam('root')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'getspnam(): name not found'
```

And here is the post-install log: 
```

2020-11-28 20:21:52,380: INFO - Installing YunoHost...
2020-11-28 20:21:52,385: DEBUG - No custom hook for action 'conf_regen' in /etc/yunohost/hooks.d/
2020-11-28 20:21:52,391: DEBUG - Executing command 'sh -c YNH_INTERFACE=api YNH_CWD=/usr/share/yunohost/hooks/conf_regen YNH_STDINFO=/tmp/tmpd_xx3C/stdinfo YNH_STDRETURN=/tmp/tmpuM8_aV/stdreturn BASH_XTRACEFD=7 /bin/bash -x "./09-nslcd" pre 1 0 /home/yunohost.conf/pending/nslcd 7>&1'
2020-11-28 20:21:52,497: DEBUG - + set -e
2020-11-28 20:21:52,498: DEBUG - + FORCE=1
2020-11-28 20:21:52,498: DEBUG - + DRY_RUN=0
2020-11-28 20:21:52,498: DEBUG - + case "$1" in
2020-11-28 20:21:52,498: DEBUG - + do_pre_regen /home/yunohost.conf/pending/nslcd
2020-11-28 20:21:52,498: DEBUG - + pending_dir=/home/yunohost.conf/pending/nslcd
2020-11-28 20:21:52,498: DEBUG - + cd /usr/share/yunohost/templates/nslcd
2020-11-28 20:21:52,498: DEBUG - + install -D -m 644 nslcd.conf /home/yunohost.conf/pending/nslcd/etc/nslcd.conf
2020-11-28 20:21:52,498: DEBUG - + exit 0
2020-11-28 20:21:52,503: DEBUG - Executing command 'sh -c YNH_INTERFACE=api YNH_CWD=/usr/share/yunohost/hooks/conf_regen YNH_STDINFO=/tmp/tmpxqQK7h/stdinfo YNH_STDRETURN=/tmp/tmpeONmRu/stdreturn BASH_XTRACEFD=7 /bin/bash -x "./46-nsswitch" pre 1 0 /home/yunohost.conf/pending/nsswitch 7>&1'
2020-11-28 20:21:52,608: DEBUG - + set -e
2020-11-28 20:21:52,608: DEBUG - + FORCE=1
2020-11-28 20:21:52,608: DEBUG - + DRY_RUN=0
2020-11-28 20:21:52,608: DEBUG - + case "$1" in
2020-11-28 20:21:52,609: DEBUG - + do_pre_regen /home/yunohost.conf/pending/nsswitch
2020-11-28 20:21:52,609: DEBUG - + pending_dir=/home/yunohost.conf/pending/nsswitch
2020-11-28 20:21:52,609: DEBUG - + cd /usr/share/yunohost/templates/nsswitch
2020-11-28 20:21:52,609: DEBUG - + install -D -m 644 nsswitch.conf /home/yunohost.conf/pending/nsswitch/etc/nsswitch.conf
2020-11-28 20:21:52,609: DEBUG - + exit 0
2020-11-28 20:21:52,610: DEBUG - Checking pending configuration which would have been applied for category 'nsswitch'…
2020-11-28 20:21:52,611: DEBUG - category nsswitch is not in categories.yml yet.
2020-11-28 20:21:52,611: DEBUG - processing pending conf '/home/yunohost.conf/pending/nsswitch/etc/nsswitch.conf' to system conf '/etc/nsswitch.conf'
2020-11-28 20:21:52,611: DEBUG - > system conf is not managed yet
2020-11-28 20:21:52,611: INFO - The configuration file '/etc/nsswitch.conf' is now managed by YunoHost (category nsswitch).
2020-11-28 20:21:52,612: DEBUG - Configuration file '/etc/nsswitch.conf' backed up to '/home/yunohost.conf/backup/etc/nsswitch.conf-20201128.192152'
2020-11-28 20:21:52,612: DEBUG - Configuration file '/etc/nsswitch.conf' updated
2020-11-28 20:21:52,612: SUCCESS - Configuration updated for 'nsswitch'
2020-11-28 20:21:52,612: DEBUG - updating conf hashes for 'nsswitch' with: {'/etc/nsswitch.conf': '4e541356b947dd940aa7548c77bfe415'}
2020-11-28 20:21:52,613: DEBUG - Checking pending configuration which would have been applied for category 'nslcd'…
2020-11-28 20:21:52,613: DEBUG - category nslcd is not in categories.yml yet.
2020-11-28 20:21:52,613: DEBUG - processing pending conf '/home/yunohost.conf/pending/nslcd/etc/nslcd.conf' to system conf '/etc/nslcd.conf'
2020-11-28 20:21:52,613: DEBUG - > system conf is not managed yet
2020-11-28 20:21:52,613: INFO - The configuration file '/etc/nslcd.conf' is now managed by YunoHost (category nslcd).
2020-11-28 20:21:52,614: DEBUG - Configuration file '/etc/nslcd.conf' backed up to '/home/yunohost.conf/backup/etc/nslcd.conf-20201128.192152'
2020-11-28 20:21:52,614: DEBUG - Configuration file '/etc/nslcd.conf' updated
2020-11-28 20:21:52,614: SUCCESS - Configuration updated for 'nslcd'
2020-11-28 20:21:52,614: DEBUG - updating conf hashes for 'nslcd' with: {'/etc/nslcd.conf': 'e8bd1e22e7b91e60ebe5b1701e159437'}
2020-11-28 20:21:52,615: DEBUG - No custom hook for action 'conf_regen' in /etc/yunohost/hooks.d/
2020-11-28 20:21:52,616: DEBUG - Executing command 'sh -c YNH_INTERFACE=api YNH_CWD=/usr/share/yunohost/hooks/conf_regen YNH_STDINFO=/tmp/tmpO2NTw9/stdinfo YNH_STDRETURN=/tmp/tmpPTl9Gk/stdreturn BASH_XTRACEFD=7 /bin/bash -x "./09-nslcd" post 1 0 /etc/nslcd.conf 7>&1'
2020-11-28 20:21:52,721: DEBUG - + set -e
2020-11-28 20:21:52,722: DEBUG - + FORCE=1
2020-11-28 20:21:52,722: DEBUG - + DRY_RUN=0
2020-11-28 20:21:52,722: DEBUG - + case "$1" in
2020-11-28 20:21:52,722: DEBUG - + do_post_regen /etc/nslcd.conf
2020-11-28 20:21:52,722: DEBUG - + regen_conf_files=/etc/nslcd.conf
2020-11-28 20:21:52,722: DEBUG - + [[ -z /etc/nslcd.conf ]]
2020-11-28 20:21:52,722: DEBUG - + service nslcd restart
2020-11-28 20:21:52,722: DEBUG - + exit 0
2020-11-28 20:21:52,726: DEBUG - Executing command 'sh -c YNH_INTERFACE=api YNH_CWD=/usr/share/yunohost/hooks/conf_regen YNH_STDINFO=/tmp/tmptFdMNN/stdinfo YNH_STDRETURN=/tmp/tmpe8f9if/stdreturn BASH_XTRACEFD=7 /bin/bash -x "./46-nsswitch" post 1 0 /etc/nsswitch.conf 7>&1'
2020-11-28 20:21:52,832: DEBUG - + set -e
2020-11-28 20:21:52,832: DEBUG - + FORCE=1
2020-11-28 20:21:52,832: DEBUG - + DRY_RUN=0
2020-11-28 20:21:52,832: DEBUG - + case "$1" in
2020-11-28 20:21:52,832: DEBUG - + do_post_regen /etc/nsswitch.conf
2020-11-28 20:21:52,832: DEBUG - + regen_conf_files=/etc/nsswitch.conf
2020-11-28 20:21:52,832: DEBUG - + [[ -z /etc/nsswitch.conf ]]
2020-11-28 20:21:52,832: DEBUG - + service unscd restart
2020-11-28 20:21:52,833: DEBUG - + exit 0
2020-11-28 20:21:52,836: DEBUG - Full log of this operation: '<a href="#/tools/logs/20201128-192152-regen_conf-2_categories" style="text-decoration:underline">Regenerate system configurations '2_categories'</a>'
2020-11-28 20:21:52,896: SUCCESS - LDAP initialized
2020-11-28 20:21:52,905: DEBUG - No custom hook for action 'conf_regen' in /etc/yunohost/hooks.d/
2020-11-28 20:21:52,907: DEBUG - Executing command 'sh -c YNH_INTERFACE=api YNH_CWD=/usr/share/yunohost/hooks/conf_regen YNH_STDINFO=/tmp/tmpnnEx7T/stdinfo YNH_STDRETURN=/tmp/tmp_vNkIs/stdreturn BASH_XTRACEFD=7 /bin/bash -x "./02-ssl" pre 1 0 /home/yunohost.conf/pending/ssl 7>&1'
2020-11-28 20:21:53,019: DEBUG - + set -e
2020-11-28 20:21:53,019: DEBUG - + ssl_dir=/usr/share/yunohost/yunohost-config/ssl/yunoCA
2020-11-28 20:21:53,019: DEBUG - + FORCE=1
2020-11-28 20:21:53,019: DEBUG - + DRY_RUN=0
2020-11-28 20:21:53,019: DEBUG - + case "$1" in
2020-11-28 20:21:53,019: DEBUG - + do_pre_regen /home/yunohost.conf/pending/ssl
2020-11-28 20:21:53,019: DEBUG - + pending_dir=/home/yunohost.conf/pending/ssl
2020-11-28 20:21:53,020: DEBUG - + cd /usr/share/yunohost/templates/ssl
2020-11-28 20:21:53,020: DEBUG - + install -D -m 644 openssl.cnf /home/yunohost.conf/pending/ssl//usr/share/yunohost/yunohost-config/ssl/yunoCA/openssl.cnf
2020-11-28 20:21:53,020: DEBUG - + exit 0
2020-11-28 20:21:53,068: DEBUG - Checking pending configuration which would have been applied for category 'ssl'…
2020-11-28 20:21:53,069: DEBUG - category ssl is not in categories.yml yet.
2020-11-28 20:21:53,069: DEBUG - processing pending conf '/home/yunohost.conf/pending/ssl/usr/share/yunohost/yunohost-config/ssl/yunoCA/openssl.cnf' to system conf '/usr/share/yunohost/yunohost-config/ssl/yunoCA/openssl.cnf'
2020-11-28 20:21:53,069: DEBUG - > system conf has been manually removed
2020-11-28 20:21:53,070: DEBUG - Configuration file '/usr/share/yunohost/yunohost-config/ssl/yunoCA/openssl.cnf' updated
2020-11-28 20:21:53,070: SUCCESS - Configuration updated for 'ssl'
2020-11-28 20:21:53,070: DEBUG - updating conf hashes for 'ssl' with: {'/usr/share/yunohost/yunohost-config/ssl/yunoCA/openssl.cnf': 'ba92bd8d56d8b021b3b0a8dbeac82b61'}
2020-11-28 20:21:53,072: DEBUG - No custom hook for action 'conf_regen' in /etc/yunohost/hooks.d/
2020-11-28 20:21:53,073: DEBUG - Executing command 'sh -c YNH_INTERFACE=api YNH_CWD=/usr/share/yunohost/hooks/conf_regen YNH_STDINFO=/tmp/tmpPuM3Gw/stdinfo YNH_STDRETURN=/tmp/tmpqrLp1l/stdreturn BASH_XTRACEFD=7 /bin/bash -x "./02-ssl" post 1 0 /usr/share/yunohost/yunohost-config/ssl/yunoCA/openssl.cnf 7>&1'
2020-11-28 20:21:53,179: DEBUG - + set -e
2020-11-28 20:21:53,179: DEBUG - + ssl_dir=/usr/share/yunohost/yunohost-config/ssl/yunoCA
2020-11-28 20:21:53,180: DEBUG - + FORCE=1
2020-11-28 20:21:53,180: DEBUG - + DRY_RUN=0
2020-11-28 20:21:53,180: DEBUG - + case "$1" in
2020-11-28 20:21:53,180: DEBUG - + do_post_regen /usr/share/yunohost/yunohost-config/ssl/yunoCA/openssl.cnf
2020-11-28 20:21:53,180: DEBUG - + regen_conf_files=/usr/share/yunohost/yunohost-config/ssl/yunoCA/openssl.cnf
2020-11-28 20:21:53,180: DEBUG - + index_txt=/usr/share/yunohost/yunohost-config/ssl/yunoCA/index.txt
2020-11-28 20:21:53,180: DEBUG - + [[ -f /usr/share/yunohost/yunohost-config/ssl/yunoCA/index.txt ]]
2020-11-28 20:21:53,180: DEBUG - + exit 0
2020-11-28 20:21:53,182: DEBUG - Full log of this operation: '<a href="#/tools/logs/20201128-192152-regen_conf-ssl" style="text-decoration:underline">Regenerate system configurations 'ssl'</a>'
2020-11-28 20:21:53,192: DEBUG - 
2020-11-28 20:21:53,194: DEBUG - 
2020-11-28 20:21:53,196: DEBUG - 
2020-11-28 20:21:53,199: DEBUG - 
2020-11-28 20:21:53,333: DEBUG - Can't load /usr/share/yunohost/yunohost-config/ssl/.rnd into RNG
139802421658752:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:98:Filename=/usr/share/yunohost/yunohost-config/ssl/.rnd
Generating a RSA private key
...............................................................................................+++++
............................................+++++
writing new private key to '/usr/share/yunohost/yunohost-config/ssl/yunoCA/ca/cakey.pem'
-----

2020-11-28 20:21:53,336: DEBUG - 
2020-11-28 20:21:53,568: DEBUG - Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.

2020-11-28 20:21:53,568: SUCCESS - Local certification authority created.
2020-11-28 20:21:53,574: DEBUG - No custom hook for action 'conf_regen' in /etc/yunohost/hooks.d/
2020-11-28 20:21:53,575: DEBUG - Executing command 'sh -c YNH_INTERFACE=api YNH_CWD=/usr/share/yunohost/hooks/conf_regen YNH_STDINFO=/tmp/tmpl2s7Wt/stdinfo YNH_STDRETURN=/tmp/tmpuRojmE/stdreturn BASH_XTRACEFD=7 /bin/bash -x "./46-nsswitch" pre 1 0 /home/yunohost.conf/pending/nsswitch 7>&1'
2020-11-28 20:21:53,682: DEBUG - + set -e
2020-11-28 20:21:53,682: DEBUG - + FORCE=1
2020-11-28 20:21:53,682: DEBUG - + DRY_RUN=0
2020-11-28 20:21:53,682: DEBUG - + case "$1" in
2020-11-28 20:21:53,683: DEBUG - + do_pre_regen /home/yunohost.conf/pending/nsswitch
2020-11-28 20:21:53,683: DEBUG - + pending_dir=/home/yunohost.conf/pending/nsswitch
2020-11-28 20:21:53,683: DEBUG - + cd /usr/share/yunohost/templates/nsswitch
2020-11-28 20:21:53,683: DEBUG - + install -D -m 644 nsswitch.conf /home/yunohost.conf/pending/nsswitch/etc/nsswitch.conf
2020-11-28 20:21:53,683: DEBUG - + exit 0
2020-11-28 20:21:53,686: DEBUG - Checking pending configuration which would have been applied for category 'nsswitch'…
2020-11-28 20:21:53,687: DEBUG - processing pending conf '/home/yunohost.conf/pending/nsswitch/etc/nsswitch.conf' to system conf '/etc/nsswitch.conf'
2020-11-28 20:21:53,687: DEBUG - > system conf is already up-to-date
2020-11-28 20:21:53,688: DEBUG - The configuration is already up-to-date for category 'nsswitch'
2020-11-28 20:21:53,688: DEBUG - No custom hook for action 'conf_regen' in /etc/yunohost/hooks.d/
2020-11-28 20:21:53,688: DEBUG - Executing command 'sh -c YNH_INTERFACE=api YNH_CWD=/usr/share/yunohost/hooks/conf_regen YNH_STDINFO=/tmp/tmp3LVqFs/stdinfo YNH_STDRETURN=/tmp/tmplQwFtN/stdreturn BASH_XTRACEFD=7 /bin/bash -x "./46-nsswitch" post 1 0 '' 7>&1'
2020-11-28 20:21:53,795: DEBUG - + set -e
2020-11-28 20:21:53,796: DEBUG - + FORCE=1
2020-11-28 20:21:53,796: DEBUG - + DRY_RUN=0
2020-11-28 20:21:53,796: DEBUG - + case "$1" in
2020-11-28 20:21:53,796: DEBUG - + do_post_regen
2020-11-28 20:21:53,796: DEBUG - + regen_conf_files=
2020-11-28 20:21:53,796: DEBUG - + [[ -z '' ]]
2020-11-28 20:21:53,796: DEBUG - + exit 0
2020-11-28 20:21:53,798: DEBUG - Full log of this operation: '<a href="#/tools/logs/20201128-192153-regen_conf-nsswitch" style="text-decoration:underline">Regenerate system configurations 'nsswitch'</a>'
2020-11-28 20:21:53,808: DEBUG - Checking if yunopr.nohost.me is managed by dyndns.yunohost.org ...
2020-11-28 20:21:53,924: DEBUG - Checking if yunopr.nohost.me is managed by dyndns.yunohost.org ...
2020-11-28 20:21:54,037: DEBUG - Checking if domain yunopr.nohost.me is available on dyndns.yunohost.org ...
2020-11-28 20:21:54,166: DEBUG - Generating DNS key... It may take a while.
2020-11-28 20:21:54,425: SUCCESS - DynDNS domain registered
2020-11-28 20:21:54,426: SUCCESS - DynDNS cron job created
2020-11-28 20:21:54,426: DEBUG - Full log of this operation: '<a href="#/tools/logs/20201128-192154-dyndns_subscribe-yunopr.nohost.me" style="text-decoration:underline">Subscribe to a YunoHost subdomain 'yunopr.nohost.me'</a>'
2020-11-28 20:21:54,521: DEBUG - Ignoring -days; not generating a certificate
Generating a RSA private key
.......................................................+++++
..................+++++
writing new private key to '/etc/yunohost/certs//yunopr.nohost.me-history/20201128.192154-selfsigned/key.pem'
-----

2020-11-28 20:21:54,528: DEBUG - Using configuration from /etc/yunohost/certs//yunopr.nohost.me-history/20201128.192154-selfsigned/openssl.cnf
Check that the request matches the signature
Signature ok
Certificate Details:
        Serial Number:
            8c:86:a4:18:e1:32:44:78:bd:a1:78:0c:37:8a:af:d7:e1:54:fe
        Validity
            Not Before: Nov 28 19:21:54 2020 GMT
            Not After : Nov 26 19:21:54 2030 GMT
        Subject:
            commonName                = yunopr.nohost.me
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            Netscape Comment: 
                OpenSSL Generated Certificate
            X509v3 Subject Key Identifier: 
                9F:7D:1D:EB:95:0B:1A:D1:CE:E9:2F:F3:51:62:61:A5:19:BF:11:E0
            X509v3 Authority Key Identifier: 
                keyid:DB:57:52:0F:4A:CC:5D:D2:F7:74:A6:75:73:D5:BC:CE:0E:71:18:88

            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Alternative Name: 
                DNS:yunopr.nohost.me, DNS:www.yunopr.nohost.me, DNS:ns.yunopr.nohost.me, DNS:xmpp-upload.yunopr.nohost.me
Certificate is to be certified until Nov 26 19:21:54 2030 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

2020-11-28 20:21:54,530: DEBUG - Enabling the certificate for domain yunopr.nohost.me ...
2020-11-28 20:21:54,530: DEBUG - Restarting services...
2020-11-28 20:21:54,539: DEBUG - Running 'systemctl restart postfix'
2020-11-28 20:21:54,805: DEBUG - Running 'systemctl restart dovecot'
2020-11-28 20:21:56,037: DEBUG - Running 'systemctl restart metronome'
2020-11-28 20:21:56,150: DEBUG - Running 'systemctl reload nginx'
2020-11-28 20:21:56,208: DEBUG - No default hook for action 'post_cert_update' in /usr/share/yunohost/hooks/
2020-11-28 20:21:56,209: DEBUG - No custom hook for action 'post_cert_update' in /etc/yunohost/hooks.d/
2020-11-28 20:21:56,210: SUCCESS - Self-signed certificate now installed for the domain 'yunopr.nohost.me'
2020-11-28 20:21:56,211: DEBUG - Full log of this operation: '<a href="#/tools/logs/20201128-192154-selfsigned_cert_install-yunopr.nohost.me" style="text-decoration:underline">Install self-signed certificate on 'yunopr.nohost.me' domain</a>'
2020-11-28 20:21:56,224: DEBUG - No default hook for action 'post_domain_add' in /usr/share/yunohost/hooks/
2020-11-28 20:21:56,225: DEBUG - No custom hook for action 'post_domain_add' in /etc/yunohost/hooks.d/
2020-11-28 20:21:56,225: SUCCESS - Domain created
2020-11-28 20:21:56,225: DEBUG - Full log of this operation: '<a href="#/tools/logs/20201128-192153-domain_add-yunopr.nohost.me" style="text-decoration:underline">Add 'yunopr.nohost.me' domain into system configuration</a>'
2020-11-28 20:21:56,285: DEBUG - 
2020-11-28 20:21:56,291: DEBUG - 
2020-11-28 20:21:56,298: DEBUG - 
2020-11-28 20:21:56,306: DEBUG - SSOwat configuration generated
2020-11-28 20:21:56,306: SUCCESS - The main domain has been changed
2020-11-28 20:21:56,306: DEBUG - Full log of this operation: '<a href="#/tools/logs/20201128-192156-domain_main_domain-yunopr.nohost.me" style="text-decoration:underline">Make 'yunopr.nohost.me' the main domain</a>'

```

**Comment by alexAubin** [comment]
Well I don't understand ... if you're defining a password for root and it ain't stored in /etc/shadow, where is it ? :| 

(I guess you don't know either but that's a very bizarre setup  ...)
