### ISSUE TITLE
intern error in diagnostics after update to ynh 4.1.4

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost/issues#1705]
After upgrade to ynh 4.1.4 diagrostics shows error:

Action
```
GET /diagnosis/show
{"full":""}
```

Traceback
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 485, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 592, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/diagnosis.py", line 99, in diagnosis_show
    add_ignore_flag_to_issues(report)
  File "/usr/lib/moulinette/yunohost/diagnosis.py", line 341, in add_ignore_flag_to_issues
    for criterias in ignore_filters:
TypeError: 'NoneType' object is not iterable
```

more "red lines" during diagnostics:
```
Diagnose fehlgeschlagen für die Kategorie 'ports':
Traceback (most recent call last):
File "/usr/lib/moulinette/yunohost/diagnosis.py", line 176, in diagnosis_run
code, report = hook_exec(path, args={"force": force}, env=None)
File "/usr/lib/moulinette/yunohost/hook.py", line 350, in hook_exec
returncode, returndata = _hook_exec_python(path, args, env, loggers)
File "/usr/lib/moulinette/yunohost/hook.py", line 463, in _hook_exec_python
ret = module.main(args, env, loggers)
File "/usr/share/yunohost/hooks/diagnosis/14-ports.py", line 116, in main
return PortsDiagnoser(args, env, loggers).diagnose()
File "/usr/lib/moulinette/yunohost/diagnosis.py", line 404, in diagnose
add_ignore_flag_to_issues(new_report)
File "/usr/lib/moulinette/yunohost/diagnosis.py", line 341, in add_ignore_flag_to_issues
for criterias in ignore_filters:
TypeError: 'NoneType' object is not iterable
```
Logs in GUI does not show any logs.

**Comment by alexAubin** [comment]
Can you share the content of

```
/etc/yunohost/diagnosis.yml
```

**Comment by AkselRocks** [comment]
```
  GNU nano 3.2                        /etc/yunohost/diagnosis.yml                                   

ignore_filters:
  dnsrecords:
  - domain: aksel.rocks
    test: domain_expiration
  ports: null
  regenconf: []
```

**Comment by alexAubin** [comment]
Hmmmokay I doubt this has really anything to do with 4.1 itself because the corresponding code did not change

Can you elaborate on what you did maybe ? I'm suspecting you tweaked the ignore/unignore stuff in the diagnosis result page ?

Not that it should have miserably crashed though, there's clearly a bug, but it helps to understand how we ended up here

Anyway, as a quick workaround you can try to remove the line written `ports: null` (or alternatively replace it with `ports: []` but that should be the same effect)

**Comment by AkselRocks** [comment]
- A few weeks/months ago I had some problems with diagnostics and ports and changed some things in diagnostics.yaml
But diagnostics worked since then.
- on 6th jan I deactivated domain expiration. I do not know if I did a diagnostics till then.
Does this help?

I will change to `ports: []` and report.

**Comment by AkselRocks** [comment]
After change (`ports: []`) diagnostics works fine.
Also Logs are visible again.

From my point the issue is solved and can be closed.
