### ISSUE TITLE
dyndns troubles. no connectivity and spammy reporting

### ISSUE THREAD

**Issue by Aaaamu** [YunoHost/issues#1719]
Hi,
since a few days, I have troubles with moulinette / dyndns. I get Mails every 2 Minutes and the dns server seems unreachable
Mail:
Cron <root@em> yunohost dyndns update >> /dev/null

Traceback (most recent call last):
  File "/usr/bin/yunohost", line 72, in <module>
    parser=parser
  File "/usr/lib/moulinette/yunohost/__init__.py", line 29, in cli
    top_parser=parser
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 120, in cli
    args, output_as=output_as, timeout=timeout
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 477, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 592, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 358, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/dyndns.py", line 219, in dyndns_update
    old_ipv4 = check_output("dig @%s +short %s" % (dyn_host, domain)) or None
  File "/usr/lib/python2.7/dist-packages/moulinette/utils/process.py", line 31, in check_output
    return subprocess.check_output(args, stderr=stderr, shell=shell, **kwargs).strip()
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'dig @dyndns.yunohost.org +short em.nohost.me' returned non-zero exit status 9
#############################################################
seems to be the same problem again? my dns was autoconfigured on yunohost installation, my domain is em.nohost.me

_Originally posted by @Aaaamu in https://github.com/YunoHost/issues/issues/807#issuecomment-762438659_

**Comment by alexAubin** [comment]
To be fixed by https://github.com/YunoHost/yunohost/pull/1140

**Comment by Aaaamu** [comment]
I tested your fixed dyndns.py and got the following back:
https://paste.yunohost.org/raw/ocopufunoz

(I backed up dyndns.py and replaced it with your new version from #1140, then ran "sudo yunohost dyndns update" and hoped nothing would explode ;)
 
...no idea if that made sense :) ignore if it doesnt

**Comment by alexAubin** [comment]
Hmyeah there was some issue in the script maybe ... fixed a few stuff, it's available in yunohost 4.1.6
