### ISSUE TITLE
Cloudflare - Certificate Origin

### ISSUE THREAD

**Issue by andretheolauret** [YunoHost/issues#1795]
Hello, I have installing custom certificate according to the documentation, and when I try to go in certificate settings from cli or webmin, it gives me this traceback :

Bonjour, j'ai installé un certificat cloudflare sur mon serveur en suivant la documentation mais quand j'essaie de cliquer sur les certificats du domaine dans le cli ou le webmin, j'obtiens cette erreur :

```
021-05-11 19:10:15,206: DEBUG - Executing command '/bin/bash -x "./15-nginx" pre 0 0 /home/yunohost.conf/pending/nginx 7>&1'
2021-05-11 19:10:15,263: DEBUG - + set -e
2021-05-11 19:10:15,263: DEBUG - + . /usr/share/yunohost/helpers
2021-05-11 19:10:15,279: DEBUG - +++ set +o
2021-05-11 19:10:15,279: DEBUG - +++ grep xtrace
2021-05-11 19:10:15,298: DEBUG - ++ readonly 'XTRACE_ENABLE=set -o xtrace'
2021-05-11 19:10:15,299: DEBUG - ++ XTRACE_ENABLE='set -o xtrace'
2021-05-11 19:10:15,435: DEBUG - + FORCE=0
2021-05-11 19:10:15,435: DEBUG - + DRY_RUN=0
2021-05-11 19:10:15,435: DEBUG - + case "$1" in
2021-05-11 19:10:15,435: DEBUG - + do_pre_regen /home/yunohost.conf/pending/nginx
2021-05-11 19:10:15,435: DEBUG - + pending_dir=/home/yunohost.conf/pending/nginx
2021-05-11 19:10:15,435: DEBUG - + cd /usr/share/yunohost/templates/nginx
2021-05-11 19:10:15,435: DEBUG - + nginx_dir=/home/yunohost.conf/pending/nginx/etc/nginx
2021-05-11 19:10:15,436: DEBUG - + nginx_conf_dir=/home/yunohost.conf/pending/nginx/etc/nginx/conf.d
2021-05-11 19:10:15,436: DEBUG - + mkdir -p /home/yunohost.conf/pending/nginx/etc/nginx/conf.d
2021-05-11 19:10:15,453: DEBUG - + cp plain/acme-challenge.conf.inc plain/global.conf plain/ssowat.conf plain/yunohost_admin.conf.inc plain/yunohost_api.conf.inc plain/yunohost_panel.conf.inc plain/yunohost_sso.conf.inc /home/yunohost.conf/pending/nginx/etc/nginx/conf.d
2021-05-11 19:10:15,500: DEBUG - ++ yunohost settings get ssowat.panel_overlay.enabled
2021-05-11 19:10:15,891: DEBUG - + panel_overlay=True
2021-05-11 19:10:15,891: DEBUG - + '[' True == false ']'
2021-05-11 19:10:15,891: DEBUG - + '[' True == False ']'
2021-05-11 19:10:15,893: DEBUG - ++ cat /etc/yunohost/current_host
2021-05-11 19:10:15,895: DEBUG - + main_domain=portail.dttechnology.fr
2021-05-11 19:10:15,903: DEBUG - ++ yunohost settings get security.nginx.compatibility
2021-05-11 19:10:16,248: DEBUG - + export compatibility=intermediate
2021-05-11 19:10:16,249: DEBUG - + compatibility=intermediate
2021-05-11 19:10:16,249: DEBUG - + ynh_render_template security.conf.inc /home/yunohost.conf/pending/nginx/etc/nginx/conf.d/security.conf.inc
2021-05-11 19:10:16,249: DEBUG - + local template_path=security.conf.inc
2021-05-11 19:10:16,249: DEBUG - + local output_path=/home/yunohost.conf/pending/nginx/etc/nginx/conf.d/security.conf.inc
2021-05-11 19:10:16,249: DEBUG - ++ dirname /home/yunohost.conf/pending/nginx/etc/nginx/conf.d/security.conf.inc
2021-05-11 19:10:16,249: DEBUG - + mkdir -p /home/yunohost.conf/pending/nginx/etc/nginx/conf.d
2021-05-11 19:10:16,249: DEBUG - + python3 -c 'import os, sys, jinja2; sys.stdout.write(
2021-05-11 19:10:16,249: DEBUG -                     jinja2.Template(sys.stdin.read()
2021-05-11 19:10:16,249: DEBUG -                     ).render(os.environ));'
2021-05-11 19:10:16,438: DEBUG - ++ yunohost domain cert-status --json
2021-05-11 19:10:16,847: WARNING - Traceback (most recent call last):
2021-05-11 19:10:16,848: WARNING -   File "/usr/bin/yunohost", line 72, in <module>
2021-05-11 19:10:16,848: WARNING -     parser=parser
2021-05-11 19:10:16,849: WARNING -   File "/usr/lib/moulinette/yunohost/__init__.py", line 25, in cli
2021-05-11 19:10:16,849: WARNING -     ret = moulinette.cli(args, output_as=output_as, timeout=timeout, top_parser=parser)
2021-05-11 19:10:16,849: WARNING -   File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 120, in cli
2021-05-11 19:10:16,849: WARNING -     args, output_as=output_as, timeout=timeout
2021-05-11 19:10:16,849: WARNING -   File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 502, in run
2021-05-11 19:10:16,850: WARNING -     ret = self.actionsmap.process(args, timeout=timeout)
2021-05-11 19:10:16,850: WARNING -   File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 600, in process
2021-05-11 19:10:16,850: WARNING -     return func(**arguments)
2021-05-11 19:10:16,850: WARNING -   File "/usr/lib/moulinette/yunohost/domain.py", line 396, in domain_cert_status
2021-05-11 19:10:16,851: WARNING -     return yunohost.certificate.certificate_status(domain_list, full)
2021-05-11 19:10:16,851: WARNING -   File "/usr/lib/moulinette/yunohost/certificate.py", line 98, in certificate_status
2021-05-11 19:10:16,851: WARNING -     status = _get_status(domain)
2021-05-11 19:10:16,851: WARNING -   File "/usr/lib/moulinette/yunohost/certificate.py", line 725, in _get_status
2021-05-11 19:10:16,852: WARNING -     elif cert_issuer.startswith("Fake LE"):
2021-05-11 19:10:16,852: WARNING - AttributeError: 'NoneType' object has no attribute 'startswith'
2021-05-11 19:10:16,892: DEBUG - + cert_status=
2021-05-11 19:10:16,893: ERROR - Échec de l’exécution du script : /usr/share/yunohost/hooks/conf_regen/15-nginx
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/hook.py", line 307, in hook_callback
    path, args=hook_args, chdir=chdir, env=env, raise_on_error=True
  File "/usr/lib/moulinette/yunohost/hook.py", line 386, in hook_exec
    raise YunohostError("hook_exec_failed", path=path)
yunohost.utils.error.YunohostError: Échec de l’exécution du script : /usr/share/yunohost/hooks/conf_regen/15-nginx
```

**Comment by zamentur** [comment]
Your certificate are correctly installed ? I mean, with a browser have you a green padlock ?
