### ISSUE TITLE
Python error on exception during YunoHost certificate renewal

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost/issues#1803]
Here is the log from the cron:

<details>
<summary>Details</summary>

```
/etc/cron.daily/yunohost-certificate-renew:
L'enregistrement DNS du domaine domain.tld est différent de l’adresse IP de ce serveur. Pour plus d'informations, veuillez consulter la catégorie "Enregistrements DNS" dans la section diagnostic. Si vous avez récemment modifié votre enregistrement 'A', veuillez attendre sa propagation (des vérificateurs de propagation DNS sont disponibles en ligne). (Si vous savez ce que vous faites, utilisez --no-checks pour désactiver ces contrôles)
Sending email with details to root ...
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/certificate.py", line 405, in certificate_renew
    _check_domain_is_ready_for_ACME(domain)
  File "/usr/lib/moulinette/yunohost/certificate.py", line 886, in _check_domain_is_ready_for_ACME
    "certmanager_domain_dns_ip_differs_from_public_ip", domain=domain
yunohost.utils.error.YunohostValidationError: L'enregistrement DNS du domaine domain.tld est différent de l’adresse IP de ce serveur. Pour plus d'informations, veuillez consulter la catégorie "Enregistrements DNS" dans la section diagnostic. Si vous avez récemment modifié votre enregistrement 'A', veuillez attendre sa propagation (des vérificateurs de propagation DNS sont disponibles en ligne). (Si vous savez ce que vous faites, utilisez --no-checks pour désactiver ces contrôles)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/yunohost", line 72, in <module>
    parser=parser
  File "/usr/lib/moulinette/yunohost/__init__.py", line 25, in cli
    ret = moulinette.cli(args, output_as=output_as, timeout=timeout, top_parser=parser)
  File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 120, in cli
    args, output_as=output_as, timeout=timeout
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 502, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 600, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/domain.py", line 415, in domain_cert_renew
    domain_list, force, no_checks, email, staging
  File "/usr/lib/moulinette/yunohost/certificate.py", line 410, in certificate_renew
    _email_renewing_failed(domain, e)
  File "/usr/lib/moulinette/yunohost/certificate.py", line 464, in _email_renewing_failed
    logs = _tail(50, "/var/log/yunohost/yunohost-cli.log")
  File "/usr/lib/moulinette/yunohost/certificate.py", line 952, in _tail
    stdin, stdout = os.popen2("tail -n %s '%s'" % (n, file_path))
AttributeError: module 'os' has no attribute 'popen2'
run-parts: /etc/cron.daily/yunohost-certificate-renew exited with return code 1
```

</details>

There is actually a glitch I can't correct with the domain DNS configuration, but the problem here in the error handling, I guess.

**Comment by alexAubin** [comment]
Should be fixed by 1227
