### ISSUE TITLE
 Update error nextcloud  20.0.8~ynh1 to 21.0.2~ynh1

### ISSUE THREAD

**Issue by danistra78** [YunoHost/issues#1827]
Hello when updating nextcloud 20.0.8~ynh1 to 21.0.2~ynh1 there was an error message:

Starting ...
Upgrade to nextcloud 21.0.2
'/tmp/tmp.C8LNX4GegD' wasn't deleted because it doesn't exist.
1/0 [--->------------------------] 0%Unable to upgrade Nextcloud
[Error] Upgrade failed.
27614 /!\ Packagers! You are probably using a lua regex. You should use a PCRE regex instead.

[wecizebone.txt](https://github.com/YunoHost/issues/files/6706213/wecizebone.txt)

**Comment by nin0-0** [comment]
I see the same error, relevant part:
``` bash
2021-06-23 15:36:39,749: DEBUG - Error: Undefined class constant 'MAJOR_VERSION' in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Utils.php:118
2021-06-23 15:36:39,749: DEBUG - Stack trace:
2021-06-23 15:36:39,749: DEBUG - #0 /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/functions.php(71): GuzzleHttp\Utils::defaultUserAgent()
2021-06-23 15:36:39,749: DEBUG - #1 /var/www/nextcloud/apps/files_external_gdrive/vendor/guzzlehttp/guzzle/src/Client.php(194): GuzzleHttp\default_user_agent()
2021-06-23 15:36:39,749: DEBUG - #2 /var/www/nextcloud/apps/files_external_gdrive/vendor/guzzlehttp/guzzle/src/Client.php(75): GuzzleHttp\Client->configureDefaults(Array)
2021-06-23 15:36:39,749: DEBUG - #3 /var/www/nextcloud/lib/private/Http/Client/ClientService.php(62): GuzzleHttp\Client->__construct()
2021-06-23 15:36:39,749: DEBUG - #4 /var/www/nextcloud/lib/private/OCS/DiscoveryService.php(55): OC\Http\Client\ClientService->newClient()
2021-06-23 15:36:39,749: DEBUG - #5 /var/www/nextcloud/lib/private/Server.php(1251): OC\OCS\DiscoveryService->__construct(Object(OC\Memcache\Factory), Object(OC\Http\Client\ClientService))
2021-06-23 15:36:39,749: DEBUG - #6 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(155): OC\Server->OC\{closure}(Object(OC\Server))
2021-06-23 15:36:39,750: DEBUG - #7 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
2021-06-23 15:36:39,750: DEBUG - #8 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(122): Pimple\Container->offsetGet('OCP\\OCS\\IDiscov...')
2021-06-23 15:36:39,750: DEBUG - #9 /var/www/nextcloud/lib/private/ServerContainer.php(137): OC\AppFramework\Utility\SimpleContainer->query('OCP\\OCS\\IDiscov...', false)
2021-06-23 15:36:39,750: DEBUG - #10 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(434): OC\ServerContainer->query('OCP\\OCS\\IDiscov...', true)
2021-06-23 15:36:39,750: DEBUG - #11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query('OCP\\OCS\\IDiscov...', true)
2021-06-23 15:36:39,750: DEBUG - #12 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
2021-06-23 15:36:39,750: DEBUG - #13 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map(Object(Closure), Array)
2021-06-23 15:36:39,750: DEBUG - #14 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
2021-06-23 15:36:39,750: DEBUG - #15 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Federation\\...')
2021-06-23 15:36:39,750: DEBUG - #16 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Federation\\...')
2021-06-23 15:36:39,750: DEBUG - #17 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(431): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Federation\\...')
2021-06-23 15:36:39,750: DEBUG - #18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Federation\\...', true)
2021-06-23 15:36:39,750: DEBUG - #19 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
2021-06-23 15:36:39,750: DEBUG - #20 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map(Object(Closure), Array)
2021-06-23 15:36:39,750: DEBUG - #21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
2021-06-23 15:36:39,750: DEBUG - #22 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Federation\\...')
2021-06-23 15:36:39,751: DEBUG - #23 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Federation\\...')
2021-06-23 15:36:39,751: DEBUG - #24 /var/www/nextcloud/lib/private/ServerContainer.php(146): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Federation\\...')
2021-06-23 15:36:39,751: DEBUG - #25 /var/www/nextcloud/lib/private/Console/Application.php(221): OC\ServerContainer->query('OCA\\Federation\\...')
2021-06-23 15:36:39,751: DEBUG - #26 /var/www/nextcloud/lib/private/Console/Application.php(136): OC\Console\Application->loadCommandsFromInfoXml(Array)
2021-06-23 15:36:39,751: DEBUG - #27 /var/www/nextcloud/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
2021-06-23 15:36:39,751: DEBUG - #28 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
2021-06-23 15:36:39,758: DEBUG - #29 {main}+ ynh_exit_properly
```

**Comment by nin0-0** [comment]
I found the culprit, I had to disinstall the google external storage app (which doesn't work anyway), reran the upgrade and works fine.

**Comment by kay0u** [comment]
@danistra78 from your logs:
> Exception: App "Collabora Online - Built-in CODE Server" cannot be installed because the following dependencies are not fulfilled: The following architectures are supported: x86_64

Could you disable the app `Collabora Online - Built-in CODE Server`, rerun the upgrade and reenable it please?

**Comment by nin0-0** [comment]
I had that one enabled and it was not blocking afaict
