### ISSUE TITLE
Backup failed with custom backup method (borg)

### ISSUE THREAD

**Issue by grenagit** [YunoHost/issues#1891]
### Backup failed with custom backup method (borg)

*Since a few days, the custom backup process does not complete and blocks the " organize_files " step...*

### Context

- Hardware: *Mini PC 64 bits*
- YunoHost version: *4.2.8.3 (stable)*
- I have access to my server: *Through SSH and the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - Use Borg Backup in local repo
  - SSH Keys

### Steps to reproduce

Run a custom backup with borg

### Expected behavior

*The problem seems to be related to the [ask confirmation for copying](https://github.com/YunoHost/yunohost/blob/dev/src/yunohost/backup.py#L1834) in case the value of [MB_ALLOWED_TO_ORGANIZE (10 MB)](https://github.com/YunoHost/yunohost/blob/76c1abf02027f9a03e5b6d874652cf531a16645a/src/yunohost/backup.py#L83) is exceeded. When I manually increase the value of [MB_ALLOWED_TO_ORGANIZE](https://github.com/YunoHost/yunohost/blob/76c1abf02027f9a03e5b6d874652cf531a16645a/src/yunohost/backup.py#L83) to 20 MB, the process normally ends !*

### Logs

```sh
Failed to format translated string 'backup_method_custom_finished': 'La méthode de sauvegarde personnalisée '{method}' est terminée' with arguments '()' and '{}, raising error: KeyError('method') (don't panic this is just a warning)
Failed to format translatable string 'backup_method_custom_finished': 'Custom backup method '{method}' finished' with arguments '()' and '{}', raising  error: KeyError('method') (don't panic this is just a warning)
Failed to format translated string 'backup_applying_method_custom': 'Appel de la méthode de sauvegarde personnalisée '{method}'...' with arguments '()' and '{}, raising error: KeyError('method') (don't panic this is just a warning)
Failed to format translatable string 'backup_applying_method_custom': 'Calling the custom backup method '{method}'...' with arguments '()' and '{}', raising  error: KeyError('method') (don't panic this is just a warning)
do_known_hosts: hostkeys_foreach failed: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/backup.py", line 1847, in _organize_files
    size=str(size),
  File "/usr/lib/python3/dist-packages/moulinette/core.py", line 354, in prompt
    return self._prompt(message, is_password, confirm, color=color)
  File "/usr/lib/python3/dist-packages/moulinette/core.py", line 377, in _notimplemented
    raise NotImplementedError("this signal is not handled")
NotImplementedError: this signal is not handled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/yunohost", line 72, in <module>
    parser=parser
  File "/usr/lib/moulinette/yunohost/__init__.py", line 25, in cli
    ret = moulinette.cli(args, output_as=output_as, timeout=timeout, top_parser=parser)
  File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 120, in cli
    args, output_as=output_as, timeout=timeout
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 502, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 600, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 380, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/backup.py", line 2288, in backup_create
    backup_manager.backup()
  File "/usr/lib/moulinette/yunohost/backup.py", line 766, in backup
    method.mount_and_backup()
  File "/usr/lib/moulinette/yunohost/backup.py", line 1707, in mount_and_backup
    self._organize_files()
  File "/usr/lib/moulinette/yunohost/backup.py", line 1850, in _organize_files
    except NotImplemented:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by alexAubin** [comment]
(ping @zamentur in case you have some idea about this)

**Comment by zamentur** [comment]
Are you using several disks or partition on this server? Have you move /home/yunohost.backup on an other disk, instead of move /home/yunohost.backup/archives ?
```
df -h
```
As a quick work around you can try to increase this value: https://github.com/YunoHost/yunohost/blob/dev/src/yunohost/backup.py#L83

**Comment by grenagit** [comment]
> Are you using several disks or partition on this server?

1 disk and 5 partitions :
- SWAP
- /
- /boot
- /home
- /backups : Borg local repo
- /boot
>Have you move /home/yunohost.backup on an other disk, instead of move /home/yunohost.backup/archives ?

No 

> ```
> df -h
> ```

```
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
udev               3,8G       0  3,8G   0% /dev
tmpfs              781M     65M  716M   9% /run
/dev/sda6           19G    9,3G  8,0G  54% /
tmpfs              3,9G   1012K  3,9G   1% /dev/shm
tmpfs              5,0M       0  5,0M   0% /run/lock
tmpfs              3,9G       0  3,9G   0% /sys/fs/cgroup
/dev/sda8           87G     35G   48G  42% /backups
/dev/sda1          232M     93M  123M  43% /boot
/dev/sda7          122G     42G   74G  37% /home
log2ram            500M     94M  407M  19% /var/log
tmpfs              781M       0  781M   0% /run/user/993
tmpfs              781M       0  781M   0% /run/user/10
```

> As a quick work around you can try to increase this value: https://github.com/YunoHost/yunohost/blob/dev/src/yunohost/backup.py#L83

Yes, I already did! Currently [MB_ALLOWED_TO_ORGANIZE](https://github.com/YunoHost/yunohost/blob/76c1abf02027f9a03e5b6d874652cf531a16645a/src/yunohost/backup.py#L83) is to 20 MB

Thanks :smiley:
