### ISSUE TITLE
4.3: evaluate_simple_js_expression explodes when re-submitting partial forms from the webadmin

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1906]
while desperatly trying to test vpnclient, I tried to disable the VPN (previously enabled + filled with the configuration file)

When clicking save, the webadmin only submits the modified values

As a consequence, during `evaluate_simple_js_expression`, `config_file` is not defined and the code miserably explodes

Dunno how to properly fix this ...

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 497, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 597, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/log.py", line 418, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/moulinette/yunohost/app.py", line 1607, in app_config_set
    return config_.set(key, value, args, args_file, operation_logger=operation_logger)
  File "/usr/lib/moulinette/yunohost/utils/config.py", line 290, in set
    self._ask()
  File "/usr/lib/moulinette/yunohost/utils/config.py", line 528, in _ask
    questions = ask_questions_and_parse_answers(section["options"], self.args)
  File "/usr/lib/moulinette/yunohost/utils/config.py", line 1250, in ask_questions_and_parse_answers
    answers[question.name] = question.ask_if_needed()
  File "/usr/lib/moulinette/yunohost/utils/config.py", line 660, in ask_if_needed
    self.visible, context=self.context
  File "/usr/lib/moulinette/yunohost/utils/config.py", line 188, in evaluate_simple_js_expression
    return evaluate_simple_ast(node, context)
  File "/usr/lib/moulinette/yunohost/utils/config.py", line 129, in evaluate_simple_ast
    value = evaluate_simple_ast(value, context)
  File "/usr/lib/moulinette/yunohost/utils/config.py", line 76, in evaluate_simple_ast
    return context[node.id]
KeyError: 'config_file'
```

**Comment by zamentur** [comment]
Should be fixed by this line: https://github.com/YunoHost/yunohost/compare/8dbc93..ca62c01#diff-107535c2894286c9f312448c0c39decc38a9950bd9c4753bb7876a1d5ff2966cR1318

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost/yunohost/commit/759b828c8a78c82f02e55f7c95fb64a24e556783
