### ISSUE TITLE
4.3 diagnosis dnsrecords crash

### ISSUE THREAD

**Issue by kay0u** [YunoHost/issues#1908]
### Describe the bug

*When I run diagnosis, I have an error on the section `dnsrecords`*
```
2021-10-18 15:03:01,403 DEBUG    yunohost.config (unknown function) - [13790.17] Config panel /usr/share/yunohost/other/config_domain.tld.toml doesn't exists
2021-10-18 15:03:01,404 ERROR    yunohost.diagnosis (unknown function) - [13790.17] Échec du diagnostic pour la catégorie 'dnsrecords': 
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/diagnosis.py", line 198, in diagnosis_run
    code, report = hook_exec(path, args={"force": force}, env=None)
  File "/usr/lib/moulinette/yunohost/hook.py", line 378, in hook_exec
    returncode, returndata = _hook_exec_python(path, args, env, loggers)
  File "/usr/lib/moulinette/yunohost/hook.py", line 489, in _hook_exec_python
    ret = module.main(args, env, loggers)
  File "/usr/share/yunohost/hooks/diagnosis/12-dnsrecords.py", line 303, in main
    return DNSRecordsDiagnoser(args, env, loggers).diagnose()
  File "/usr/lib/moulinette/yunohost/diagnosis.py", line 459, in diagnose
    items = list(self.run())
  File "/usr/share/yunohost/hooks/diagnosis/12-dnsrecords.py", line 38, in run
    domain == main_domain,
  File "/usr/share/yunohost/hooks/diagnosis/12-dnsrecords.py", line 71, in check_domain
    domain, include_empty_AAAA_if_no_ipv6=True
  File "/usr/lib/moulinette/yunohost/dns.py", line 171, in _build_dns_conf
    for domain in [base_domain] + subdomains
  File "/usr/lib/moulinette/yunohost/dns.py", line 171, in <dictcomp>
    for domain in [base_domain] + subdomains
  File "/usr/lib/moulinette/yunohost/domain.py", line 439, in domain_config_get
    return config.get(key, mode)
  File "/usr/lib/moulinette/yunohost/utils/config.py", line 250, in get
    raise YunohostValidationError("config_no_panel")
yunohost.utils.error.YunohostValidationError: Aucun panneau de configuration trouvé.
```

### Context

- Hardware: *computer*
- YunoHost version: 4.3.1.5
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: switch to testing

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost/yunohost/commit/341059d07da0c5a34f0bbb4e735c5d819dffc5c8
