### ISSUE TITLE
Drag and drop is failing in import users field

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost/issues#1935]
In the **webadmin/users/import users**, drag and drop of a CSV file outputs the following error: `the following arguments are required: csvfile`

Edit: I tried again in YNH 12.0.6, exporting my users list as CSV and importing it (with `Mettre à jour les comptes existants` and `Supprimer les comptes non répertoriés` set to `non`)

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 473, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 499, in process
    arguments = vars(self.parser.parse_args(args, **kwargs))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 687, in parse_args
    ret = parser.parse_args(args, ret)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 232, in parse_args
    return self._parser.parse_args(arg_strings, namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 1874, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 1907, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2122, in _parse_known_args
    stop_index = consume_positionals(start_index)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2078, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.11/argparse.py", line 1967, in take_action
    argument_values = self._get_values(action, argument_strings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/__init__.py", line 267, in _get_values
    value = super(ExtendedArgumentParser, self)._get_values(action, arg_strings)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2501, in _get_values
    value = self._get_value(action, arg_string)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2534, in _get_value
    result = type_func(arg_string)
             ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dXNlcm5hbWU7Zmlyc3RuYW1lO2xhc3RuYW1lO3Bhc3N3b3JkO21haWw7bWFpbC1hbGlhczttYWlsLWZvcndhcmQ7bWFpbGJveC1xdW90YTtncm91cHMNCmVyaWM7w4lyaWM7R2FzcGFyOztlcmljQGVyaWNhbmRtYXJpZS5mcjs7OzA7YWRtaW5zDQptYXJpZTtNYXJpZTtHYXNwYXI7O21hcmllQGVyaWNhbmRtYXJpZS5mcjs7OzA7'
```

**Comment by zamentur** [comment]
Duplicate https://github.com/YunoHost/issues/issues/2764
