### ISSUE TITLE
utf-8 decoding error while attempting to read metronome log

### ISSUE THREAD

**Issue by muello** [YunoHost/issues#2002]
From the web admin interface, when I click Services > metronome I get:

```Error: "500" Internal Server Error

Action: "GET" /yunohost/api/services/metronome/log?number=50&locale=en

Error message:
Unexpected server error

Traceback

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 494, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 599, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/service.py", line 555, in service_log
    result[log_path] = _tail(log_path, number)
  File "/usr/lib/moulinette/yunohost/service.py", line 817, in _tail
    lines = f.read().splitlines()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 115: invalid continuation byte
```

I get essentially the same traceback from the CLI with ```$ sudo yunohost service log metronome```

**Comment by ericgeldmacher** [comment]
I came across a similar issue here. #2156
Submitted a PR that I think will fix your issue too. https://github.com/YunoHost/yunohost/pull/1606
