### ISSUE TITLE
Config Panel regression for example with hotspot

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#2099]
### Describe the bug

The hotspot config panel seems broken since 11.1.

### Context

- Hardware: Laptop with proprietary usb antenna
- YunoHost version: 11.1.1.2
- I have access to my server: yes
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: just in testing

### To reproduce

Go to the config panel, deactivate or activate it and "save".
You will get the error bellow

### Expected behavior

No error and the wifi up

### Logs

After licking save on config panel:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 460, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 586, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 411, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 1631, in app_config_set
    return config_.set(key, value, args, args_file, operation_logger=operation_logger)
  File "/usr/lib/python3/dist-packages/yunohost/utils/config.py", line 418, in set
    self._ask()
  File "/usr/lib/python3/dist-packages/yunohost/utils/config.py", line 684, in _ask
    and not evaluate_simple_js_expression(
  File "/usr/lib/python3/dist-packages/yunohost/utils/config.py", line 190, in evaluate_simple_js_expression
    return evaluate_simple_ast(node, context)
  File "/usr/lib/python3/dist-packages/yunohost/utils/config.py", line 140, in evaluate_simple_ast
    return operators[type(node.op)](evaluate_simple_ast(node.operand, context))
  File "/usr/lib/python3/dist-packages/yunohost/utils/config.py", line 78, in evaluate_simple_ast
    return context[node.id]
KeyError: 'no_antenna'
```

**Comment by zamentur** [comment]
I found a first fix, but i have a second bug: non main panel of hotspot are not displayed in CLI !

The reason: 
```
# yunohost tools shell
Warning: The ldap interface is available in this context
Warning: You don't have IPython installed, consider installing it as it is way better than the standard shell.
Warning: Falling back on the standard shell.
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from yunohost.utils.config import evaluate_simple_js_expression
>>> evaluate_simple_js_expression("! no_antenna", context={"no_antenna": {"value": False}})
False
```
Note: the context here is given like it's given by the code dedicated to display or not a section.

**Comment by alexAubin** [comment]
Corresponding fix got merged ... though the pipeline is now broken :|
