### ISSUE TITLE
Web interface not working

### ISSUE THREAD

**Issue by xeruf** [YunoHost/issues#2105]
### Describe the bug

I just restarted my own freshly installed yunohost server running on an LXC container in Proxmox.
The web interface at my configure domain is not online, and `lsof -i` shows no service listening on port 80 or 443.
The diagnosis tells me that `slapd` fails to start, but the logs for it are empty :/

### Logs

```
# yunohost diagnosis run
Info: (Cache still valid for Base system diagnosis. Won't re-diagnose it yet!)
Info: (Cache still valid for Internet connectivity diagnosis. Won't re-diagnose it yet!)
Warning: The LDAP service is down, attempt to restart it...
Job for slapd.service failed because the control process exited with error code.
See "systemctl status slapd.service" and "journalctl -xe" for details.
^[
Error: Diagnosis failed for category 'dnsrecords': 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1204, in _apply_method_s
    return func(self,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 467, in sasl_interactive_bind_s
    return self._ldap_call(self._l.sasl_interactive_bind_s,who,auth,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls),sasl_fla
gs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 93, in connect
    con = _reconnect()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 89, in _reconnect
    con.sasl_non_interactive_bind_s("EXTERNAL")
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 477, in sasl_non_interactive_bind_s
    self.sasl_interactive_bind_s('',auth,serverctrls,clientctrls,sasl_flags)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1235, in sasl_interactive_bind_s
    res = self._apply_method_s(SimpleLDAPObject.sasl_interactive_bind_s,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1208, in _apply_method_s
    self.reconnect(self._uri,retry_max=self._retry_max,retry_delay=self._retry_delay)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1176, in reconnect
    self._apply_last_bind()
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1146, in _apply_last_bind
    SimpleLDAPObject.simple_bind_s(self, None, None)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 445, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 439, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1204, in _apply_method_s
    return func(self,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 467, in sasl_interactive_bind_s
    return self._ldap_call(self._l.sasl_interactive_bind_s,who,auth,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls),sasl_fla
gs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 100, in connect
    con = _reconnect()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 89, in _reconnect
    con.sasl_non_interactive_bind_s("EXTERNAL")
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 477, in sasl_non_interactive_bind_s
    self.sasl_interactive_bind_s('',auth,serverctrls,clientctrls,sasl_flags)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1235, in sasl_interactive_bind_s
    res = self._apply_method_s(SimpleLDAPObject.sasl_interactive_bind_s,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1208, in _apply_method_s
    self.reconnect(self._uri,retry_max=self._retry_max,retry_delay=self._retry_delay)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1176, in reconnect
    self._apply_last_bind()
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1146, in _apply_last_bind
    SimpleLDAPObject.simple_bind_s(self, None, None)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 445, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 439, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/diagnosis.py", line 196, in diagnosis_run
    code, report = diagnoser.diagnose(force=force)
  File "/usr/lib/python3/dist-packages/yunohost/diagnosis.py", line 449, in diagnose
    items = list(self.run())
  File "/usr/lib/python3/dist-packages/yunohost/diagnosers/12-dnsrecords.py", line 39, in run
    major_domains = domain_list(exclude_subdomains=True)["domains"]
  File "/usr/lib/python3/dist-packages/yunohost/domain.py", line 68, in domain_list
    ldap = _get_ldap_interface()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py",                                              line 45, in _get_ldap_interface
    _ldap_interface = LDAPInterface()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 82, in __init__
    self.connect()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 102, in connect
    raise YunohostError(
yunohost.utils.error.YunohostError: Service slapd is not running but is required to perform this action ... You can try to investigate 
what's happening with 'systemctl status slapd'

Warning: No diagnosis cache yet for category 'dnsrecords'
Warning: No diagnosis cache yet for category 'dnsrecords'
Error: Found 7 significant issue(s) related to Ports exposure!
Warning: The LDAP service is down, attempt to restart it...
Job for slapd.service failed because the control process exited with error code.
See "systemctl status slapd.service" and "journalctl -xe" for details.
Error: Diagnosis failed for category 'web': 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1204, in _apply_method_s
    return func(self,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 467, in sasl_interactive_bind_s
    return self._ldap_call(self._l.sasl_interactive_bind_s,who,auth,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls),sasl_fla
gs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 93, in connect
    con = _reconnect()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 89, in _reconnect
    con.sasl_non_interactive_bind_s("EXTERNAL")
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 477, in sasl_non_interactive_bind_s
    self.sasl_interactive_bind_s('',auth,serverctrls,clientctrls,sasl_flags)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1235, in sasl_interactive_bind_s
    res = self._apply_method_s(SimpleLDAPObject.sasl_interactive_bind_s,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1208, in _apply_method_s
    self.reconnect(self._uri,retry_max=self._retry_max,retry_delay=self._retry_delay)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1176, in reconnect
    self._apply_last_bind()
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1146, in _apply_last_bind
    SimpleLDAPObject.simple_bind_s(self, None, None)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 445, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 439, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1204, in _apply_method_s
    return func(self,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 467, in sasl_interactive_bind_s
    return self._ldap_call(self._l.sasl_interactive_bind_s,who,auth,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls),sasl_fla
gs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 100, in connect
    con = _reconnect()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 89, in _reconnect
    con.sasl_non_interactive_bind_s("EXTERNAL")
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 477, in sasl_non_interactive_bind_s
    self.sasl_interactive_bind_s('',auth,serverctrls,clientctrls,sasl_flags)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1235, in sasl_interactive_bind_s
    res = self._apply_method_s(SimpleLDAPObject.sasl_interactive_bind_s,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1208, in _apply_method_s
    self.reconnect(self._uri,retry_max=self._retry_max,retry_delay=self._retry_delay)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1176, in reconnect
    self._apply_last_bind()
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1146, in _apply_last_bind
    SimpleLDAPObject.simple_bind_s(self, None, None)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 445, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 439, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/diagnosis.py", line 196, in diagnosis_run
    code, report = diagnoser.diagnose(force=force)
  File "/usr/lib/python3/dist-packages/yunohost/diagnosis.py", line 449, in diagnose
    items = list(self.run())
  File "/usr/lib/python3/dist-packages/yunohost/diagnosers/21-web.py", line 25, in run
    all_domains = domain_list()["domains"]
  File "/usr/lib/python3/dist-packages/yunohost/domain.py", line 68, in domain_list
    ldap = _get_ldap_interface()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 45, in _get_ldap_interface
    _ldap_interface = LDAPInterface()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 82, in __init__
    self.connect()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 102, in connect
    raise YunohostError(
yunohost.utils.error.YunohostError: Service slapd is not running but is required to perform this action ... You can try to investigate what's ha
ppening with 'systemctl status slapd'

Warning: The LDAP service is down, attempt to restart it...
Job for slapd.service failed because the control process exited with error code.
See "systemctl status slapd.service" and "journalctl -xe" for details.
Error: Diagnosis failed for category 'mail': 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1204, in _apply_method_s
    return func(self,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 467, in sasl_interactive_bind_s
    return self._ldap_call(self._l.sasl_interactive_bind_s,who,auth,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls),sasl_fla
gs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 93, in connect
    con = _reconnect()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 89, in _reconnect
    con.sasl_non_interactive_bind_s("EXTERNAL")
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 477, in sasl_non_interactive_bind_s
    self.sasl_interactive_bind_s('',auth,serverctrls,clientctrls,sasl_flags)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1235, in sasl_interactive_bind_s
    res = self._apply_method_s(SimpleLDAPObject.sasl_interactive_bind_s,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1208, in _apply_method_s
    self.reconnect(self._uri,retry_max=self._retry_max,retry_delay=self._retry_delay)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1176, in reconnect
    self._apply_last_bind()
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1146, in _apply_last_bind
    SimpleLDAPObject.simple_bind_s(self, None, None)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 445, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 439, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1204, in _apply_method_s
    return func(self,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 467, in sasl_interactive_bind_s
    return self._ldap_call(self._l.sasl_interactive_bind_s,who,auth,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls),sasl_fla
gs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 100, in connect
    con = _reconnect()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 89, in _reconnect
    con.sasl_non_interactive_bind_s("EXTERNAL")
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 477, in sasl_non_interactive_bind_s
    self.sasl_interactive_bind_s('',auth,serverctrls,clientctrls,sasl_flags)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1235, in sasl_interactive_bind_s
    res = self._apply_method_s(SimpleLDAPObject.sasl_interactive_bind_s,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1208, in _apply_method_s
    self.reconnect(self._uri,retry_max=self._retry_max,retry_delay=self._retry_delay)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1176, in reconnect
    self._apply_last_bind()
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1146, in _apply_last_bind
    SimpleLDAPObject.simple_bind_s(self, None, None)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 445, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 439, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 331, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 315, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 111, 'info': 'Connection refused'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/diagnosis.py", line 196, in diagnosis_run
    code, report = diagnoser.diagnose(force=force)
  File "/usr/lib/python3/dist-packages/yunohost/diagnosis.py", line 449, in diagnose
    items = list(self.run())
  File "/usr/lib/python3/dist-packages/yunohost/diagnosers/24-mail.py", line 33, in run
    self.mail_domains = domain_list()["domains"]
  File "/usr/lib/python3/dist-packages/yunohost/domain.py", line 68, in domain_list
    ldap = _get_ldap_interface()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 45, in _get_ldap_interface
    _ldap_interface = LDAPInterface()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 82, in __init__
    self.connect()
  File "/usr/lib/python3/dist-packages/yunohost/utils/ldap.py", line 102, in connect
    raise YunohostError(
yunohost.utils.error.YunohostError: Service slapd is not running but is required to perform this action ... You can try to investigate what's ha
ppening with 'systemctl status slapd'

Error: Found 11 significant issue(s) related to Services status check!
Error: Found 1 significant issue(s) related to System resources!
Warning: Found 2 item(s) that could be improved for System configurations.
Warning: The LDAP service is down, attempt to restart it...
Job for slapd.service failed because the control process exited with error code.
See "systemctl status slapd.service" and "journalctl -xe" for details.
Error: Failed to read info for jellyfin : Service slapd is not running but is required to perform this action ... You can try to investigate wha
t's happening with 'systemctl status slapd'
Warning: The LDAP service is down, attempt to restart it...
Job for slapd.service failed because the control process exited with error code.
See "systemctl status slapd.service" and "journalctl -xe" for details.
Error: Failed to read info for syncthing : Service slapd is not running but is required to perform this action ... You can try to investigate wh
at's happening with 'systemctl status slapd'
Success! Everything looks OK for Applications!
Warning: To see the issues found, you can go to the Diagnosis section of the webadmin, or run 'yunohost diagnosis show --issues --human-readable
' from the command-line.
```

**Comment by alexAubin** [comment]
Yeah considering your previous bug report I'm not surprised that additional things are fucked up ...

I guess you can have a look at `systemctl status slapd` but at this point this doesnt sounds like a Yunohost issue ...

**Comment by xeruf** [comment]
weird, it was running fine after installation
