### ISSUE TITLE
Can't list backups or upgrade apps if a backup file is invalid

### ISSUE THREAD

**Issue by rakoo** [YunoHost/issues#2118]
### Describe the bug

Because I don't have enough space on my VPS to hold a full backup, I had to put it in a remote server and mount it on my yunohost server. After that I just put a symlink inside the backup dir (`/home/yunohost.backup`) to the archive (say `/mnt/remote/path/to/backup/file.tar`). It all worked well until the folder was unmounted, at which point 2 things weren't possible anymore:

- I can't open the list of backups (and make a new backup), here's the stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 460, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 586, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/backup.py", line 2386, in backup_list
    archives = sorted(archives, key=lambda x: os.path.getctime(x))
  File "/usr/lib/python3/dist-packages/yunohost/backup.py", line 2386, in <lambda>
    archives = sorted(archives, key=lambda x: os.path.getctime(x))
  File "/usr/lib/python3.9/genericpath.py", line 65, in getctime
    return os.stat(filename).st_ctime
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/remote/path/to/backup/file.tar'
```

- I can see the list of packages to upgrade, but I can't upgrade them, because it tries to do a backup first and fails for the same problem:

```
Traceback (most recent call last):
File "/usr/bin/yunohost", line 71, in
yunohost.cli(
File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 25, in cli
ret = moulinette.cli(
File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 111, in cli
Cli(
File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 505, in run
ret = self.actionsmap.process(args, timeout=timeout)
File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 586, in process
return func(**arguments)
File "/usr/lib/python3/dist-packages/yunohost/backup.py", line 2386, in backup_list
archives = sorted(archives, key=lambda x: os.path.getctime(x))
File "/usr/lib/python3/dist-packages/yunohost/backup.py", line 2386, in
archives = sorted(archives, key=lambda x: os.path.getctime(x))
File "/usr/lib/python3.9/genericpath.py", line 65, in getctime
return os.stat(filename).st_ctime
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/remote/path/to/backup/file.tar'
Traceback (most recent call last):
File "/usr/bin/yunohost", line 71, in
yunohost.cli(
File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 25, in cli
ret = moulinette.cli(
File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 111, in cli
Cli(
File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 505, in run
ret = self.actionsmap.process(args, timeout=timeout)
File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 586, in process
return func(**arguments)
File "/usr/lib/python3/dist-packages/yunohost/log.py", line 419, in func_wrapper
result = func(*args, **kwargs)
File "/usr/lib/python3/dist-packages/yunohost/backup.py", line 2211, in backup_create
if name and name in backup_list()["archives"]:
File "/usr/lib/python3/dist-packages/yunohost/backup.py", line 2386, in backup_list
archives = sorted(archives, key=lambda x: os.path.getctime(x))
File "/usr/lib/python3/dist-packages/yunohost/backup.py", line 2386, in
archives = sorted(archives, key=lambda x: os.path.getctime(x))
File "/usr/lib/python3.9/genericpath.py", line 65, in getctime
return os.stat(filename).st_ctime
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/remote/path/to/backup/file.tar'
Backup failed, the upgrade process was aborted.
```

Of course I could remount my remote server, or delete the invalid symlink, but I still believe yunohost should be able to hide or mark as invalid the invalid backup, but at least make a new backup for upgrading an app shouldn't be blocked

### Context

- Hardware: OVH VPS
- YunoHost version: 11.0.10.2
- I have access to my server: Through SSH and webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance? no
- Using, or trying to install package version/branch: no specific branch chosen
- If upgrading, current YunoHost version: 11.0.10.2 (but not upgrading)

### To reproduce

- Create invalid symlink in `/home/yunohost.backup` (invalid meaning pointing to a file that doesn't exist
- Try to list backups or to upgrade an app

### Expected behavior

- The invalid backup file is hidden or marked as invalid
- The app can be upgraded

### Logs

There's nothing much more than what is already posted

**Comment by SpencerDub** [comment]
This has tripped me up in the past too, and made backing up and upgrading my server *much* more of a hassle than necessary.

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/yunohost/commit/a95d10e50c5b60aac7623fa1acc430799686a79d ...
