### ISSUE TITLE
Domains DNS tab throws 500 error for Google Domain

### ISSUE THREAD

**Issue by mdeabreu** [YunoHost/issues#2147]
### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.1.6.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

I've got a domain registered through domains.google.com, which is also where I control the DNS entries. I can successfully add and use the domain in YunoHost however to get the required DNS entries I have to use the command line tools to show the suggestions. This is because when I use the webadmin to view the DNS tab a 500 internal error is thrown.

### To reproduce

- Open webadmin, go to Domains, select domain registered through domains.google.com
- click the DNS tab
- experience a 500 error

### Expected behavior

The tab should load correctly and show the DNS entries required to set up the domain for YunoHost. As a workaround the terminal can be used to output the suggested DNS entries.

### Logs

When the 500 internal error pops up there is a modal window with the following information.

```
[POST] /domains/example.com/dns/push?dry_run
YunoHost encountered an internal error
Really sorry about that.
You should look for help on [the forum](https://forum.yunohost.org/) or [the chat](https://chat.yunohost.org/) to fix the situation, or report the bug on [the bugtracker](https://github.com/YunoHost/issues).
The following information might be useful for the person helping you:
Error: "500"

Action: "POST" /yunohost/api/domains/example.com/dns/push?dry_run

Error message:
Unexpected server error

Traceback

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 457, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 584, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/domain.py", line 733, in domain_dns_push
    return domain_dns_push(domain, dry_run, force, purge)
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 410, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/yunohost/dns.py", line 716, in domain_dns_push
    client = LexiconClient(query)
  File "/usr/lib/python3/dist-packages/lexicon/client.py", line 77, in __init__
    self.provider = provider_class(self.config)
  File "/usr/lib/python3/dist-packages/lexicon/providers/googleclouddns.py", line 75, in __init__
    if self._get_provider_option("auth_service_account_info").startswith("file::"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by alexAubin** [comment]
hmmm but I suspect that this is *after* trying to add the crendentials, right ?

**Comment by mdeabreu** [comment]
I didn't have any option to enter credentials for the domain. This was the default/main domain so it was entered during the post install step, then I went to get the DNS information and hit that 500 error. No chance to enter credentials.

**Comment by irrweg** [comment]
The same issues I also have with my fresh installed YunoHost, when I added the Main Domain at the beginning which is from domains.google.com . I also didn't have a Option to add credentials while using that domain.

This Error shows up every time you Visit the DNS Page of that Main Domain.
Seems like adding a Sub-Domain to the Main does not throw this Error when visiting the Sub-Domain DNS Page.

Also the the link provided to the Documentary for Google Cloud DNS API does not exit: https://yunohost.org/registar_api_googleclouddns

![Documentary](https://user-images.githubusercontent.com/345180/219940374-2dcf9579-ea23-445f-9f8d-258becc3a8de.png)
