### ISSUE TITLE
Decoding errors not handled when trying to read service logs.

### ISSUE THREAD

**Issue by ericgeldmacher** [YunoHost/issues#2156]
### Describe the bug

I recieve the following error when accessing the `my.url/yunohost/admin/#/services/gotosocial`.
I have not encountered the error with other services, but I'm not sure if the decoding errors should be handled here, or if how logs are written should be handled differently in gotosocial.

*Edit: *Looks like this is not unique to gotosocial (#2002) so maybe it would be better to handle them here*

Also after clicking "Ok" to close the dialog box, the rest of the elements on the page do not render, so you are unable to stop, start, or restart the service from the web admin panel.

<img width="620" alt="Screen Shot 2023-02-22 at 12 06 33 PM" src="https://user-images.githubusercontent.com/1066985/220723088-10d7c4c8-aee8-431f-9071-8c7751fdd961.png">

**Error:** `"500" Internal Server Error`  
**Action:** `"GET" /yunohost/api/services/gotosocial/log?number=50&locale=en`

**Traceback**

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 457, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 584, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/service.py", line 528, in service_log
    result[log_path] = _tail(log_path, number)
  File "/usr/lib/python3/dist-packages/yunohost/service.py", line 791, in _tail
    lines = f.read().splitlines()
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 14912684: invalid continuation byte
```

I was able to resolve the issue on my system by replacing
`f = open(file)` [(service.py L778)](https://github.com/YunoHost/yunohost/blob/debian/11.1.10/src/service.py#L778)

with
`f = open(file, errors='ignore')`  
or  
`f = open(file, errors='replace')`

in the [`yunohost/service.py`](https://github.com/YunoHost/yunohost/blob/debian/11.1.10/src/service.py#L778) package

### Context

- Hardware: VPS
- YunoHost version: 11.1.0
- I have access to my server: Through SSH, webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: no

### To reproduce

From the web admin panel navigate to "Tools" > "Services" > "gotosocial"

### Expected behavior

Should show a overview of the service and recent logs. Decoding errors should be handled.

I was able to resolve the issue on my system by replacing
`f = open(file)` [(service.py L778)](https://github.com/YunoHost/yunohost/blob/debian/11.1.10/src/service.py#L778)

with
`f = open(file, errors='ignore')`  
or  
`f = open(file, errors='replace')`

in the [`yunohost/service.py`](https://github.com/YunoHost/yunohost/blob/debian/11.1.10/src/service.py#L778) package

### Logs

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 457, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 584, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/service.py", line 528, in service_log
    result[log_path] = _tail(log_path, number)
  File "/usr/lib/python3/dist-packages/yunohost/service.py", line 791, in _tail
    lines = f.read().splitlines()
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 14912684: invalid continuation byte
```

**Comment by ericgeldmacher** [comment]
Looks like this may be the same issue here: #2002

**Comment by ericgeldmacher** [comment]
I confirmed that the proposed workaround also fixes the error when running `$ sudo yunohost service log gotosocial` as described in the other issue.
