### ISSUE TITLE
[manifest v2] Incorrect conversion of multiple ports

### ISSUE THREAD

**Issue by fflorent** [YunoHost/issues#2169]
### Describe the bug

When running `convert_app_to_packaging_v2.py`, the manifest.toml file generated contains a section `[resources.ports]` as expected.
However, the keys in `[resources.ports]` should not contain quotes if they contain dots.

### To reproduce

1. Clone loki_ynh: `git clone https://github.com/YunoHost-Apps/loki_ynh/`
2. Run `python3 PATH/TO/tools/packaging_v2/convert_app_to_packaging_v2.py loki_ynh`
3. Attempt to install loki, it fails with this error:
```
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 77, in <module>
    yunohost.cli(
  File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 41, in cli
    ret = moulinette.cli(
  File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 110, in cli
    Cli(
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 503, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 580, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 410, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 1178, in app_install
    raise e
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 1172, in app_install
    AppResourceManager(app_instance_name, wanted=manifest, current={}).apply(
  File "/usr/lib/python3/dist-packages/yunohost/utils/resources.py", line 53, in apply
    todos = list(self.compute_todos())
  File "/usr/lib/python3/dist-packages/yunohost/utils/resources.py", line 129, in compute_todos
    wanted_resource = AppResourceClassesByType[name](infos, self.app, self)
  File "/usr/lib/python3/dist-packages/yunohost/utils/resources.py", line 905, in __init__
    properties[port].update(infos)
TypeError: 'int' object is not iterable
```

This is due to the manifest having quotes for ports keys:

```toml
...

    [resources.ports]
    "http.default" = 3100
    "grpc.default" = 9096
    "promtail.default" = 9080
```

### Expected behavior

manifest.toml should output this:

```toml
...

    [resources.ports]
    "http.default" = 3100
    "grpc.default" = 9096
    "promtail.default" = 9080
```

**Comment by fflorent** [comment]
Note: I think we can use `tomlkit.key` for dotted-keys:

```
table.add(tomlkit.key(["http", "default"]), 3100);
```

This should help for having the expected output and get rid of this hack:
https://github.com/YunoHost/apps/blob/4cab9ecc4565f559091fde2dc26b1e149995379d/tools/packaging_v2/convert_app_to_packaging_v2.py#L215-L219

However, unless I miss something, we face this bug from tomlkit:
https://github.com/sdispater/tomlkit/issues/273

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/apps/commit/f3ec4fe4d008813f93ea7d249187ff38cf9df15e (using the same hack, I investigated at some point but didnt found any better workaround, feel free to dig deeper)

**Comment by fflorent** [comment]
That's indeed a good workaround until we can do better :)
