### ISSUE TITLE
Applying a config with a readonly type option fails with AttributeError

### ISSUE THREAD

**Issue by Tagadda** [YunoHost/issues#2220]
### Describe the bug

Since 11.2, applying a config with a readonly type (`alert`, `display_text`, `markdown`) option fails with AttributeError.
This happens on the webadmin and on the CLI.

### Context

- YunoHost version: 11.2.1

### To reproduce

- On CLI :
    1. Run `yunohost settings set security`
    2. Press enter until no options left

- On the Webadmin
    1. Browse Tools -> YunoHost settings
    2. Click "Save"

### Logs

Example from Webadmin :
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 453, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 580, in process
    return func(**arguments)
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 410, in func_wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/yunohost/settings.py", line 88, in settings_set
    return settings.set(key, value, args, args_file, operation_logger=operation_logger)
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 205, in set
    self._ask()
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 609, in _ask
    {
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 612, in <dictcomp>
    if question.value is not None
AttributeError: 'AlertOption' object has no attribute 'value'
```

**Comment by Tagadda** [comment]
Fixed by https://github.com/YunoHost/yunohost/commit/e1ceb084c3df75e37be4fbde97c075ee75d775cf
