### ISSUE TITLE
Error with the POP3 activation

### ISSUE THREAD

**Issue by stilobique** [YunoHost/issues#2282]
### Describe the bug

Hello,
from the web admin, activate the POP3 protocol, give an issue.

### Context
Test with 3 instances, all setupo with the latest yuno release (11.2.5).
- Raspberry
- VPS Contabo
- Private PC

### To reproduce
Call the setup with the CLI:
```
yunohost settings set email.pop3.pop3_enabled
```

From the webadmin:
1. Tools
2. Yunohost Settings
3. Emails
4. Enable POP3

### Logs
[Show the completed log](https://paste.yunohost.org/raw/qazepeyima).
```
2023-11-08 21:34:18,215: DEBUG - + python3 -c 'from yunohost.app import regen_mail_app_user_config_for_dovecot_and_postfix as r; r(only="dovecot")'
2023-11-08 21:34:18,543: DEBUG - + '[' -z /etc/dovecot/dovecot.conf ']'
2023-11-08 21:34:18,544: DEBUG - + [[ /etc/dovecot/dovecot.conf =~ dovecot\.sieve ]]
2023-11-08 21:34:18,544: DEBUG - + systemctl restart dovecot
2023-11-08 21:34:19,920: WARNING - Job for dovecot.service failed because the control process exited with error code.
2023-11-08 21:34:19,922: WARNING - See "systemctl status dovecot.service" and "journalctl -xe" for details.
2023-11-08 21:34:20,927: ERROR - Échec de l'exécution du script : /usr/share/yunohost/hooks/conf_regen/25-dovecot
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/hook.py", line 298, in hook_callback
    hook_return = hook_exec(
  File "/usr/lib/python3/dist-packages/yunohost/hook.py", line 410, in hook_exec
    raise YunohostError("hook_exec_failed", path=path)
yunohost.utils.error.YunohostError: Échec de l'exécution du script : /usr/share/yunohost/hooks/conf_regen/25-dovecot
2023-11-08 21:34:20,934: DEBUG - Journal complet de cette opération : '<a href="#/tools/logs/20231108-213414-regen_conf-dovecot" style="text-decoration:underline"> Régénérer les configurations du système 'dovecot' </a>'
2023-11-08 21:34:22,943: SUCCESS - Config updated as expected
```

### Another info
To solved the issue, I make this folder:
1. `/usr/lib/dovecot/pop3`
2. `/usr/lib/dovecot/pop3-login`

And it's solved. [Thanks the community to give the solution](https://forum.yunohost.org/t/dovecot-stopped-working-pop3-problems/23880/6).

**Comment by alexAubin** [comment]
Fixed in bookworm via https://github.com/YunoHost/yunohost/commit/1cbc30e0d509569d79e780ac7d94787949cb32dd
