### ISSUE TITLE
CI: comments in the manifest.toml are generating errors

### ISSUE THREAD

**Issue by OniriCorpe** [YunoHost/issues#2381]
### Describe the bug

if a `manifest.toml` have comments
```text
# like this
[upstream] # or like this
```

the CI will generate errors before each test:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '#'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'or'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'like'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'this'
```

### To reproduce

put any comment in a manifest.toml and launch CI tests

### Expected behavior

CI ignores `manifest.toml` comments

### Logs

for example with this `manifest.toml`: https://github.com/YunoHost-Apps/pyinventory_ynh/blob/a6860459fb7bb8beb59b907e829663705f20f80d/manifest.toml

```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '#'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '__DEFAULT_FROM_EMAIL__'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '#'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '__ADMIN_EMAIL__'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '#'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '__DEBUG_ENABLED__'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'will'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'be'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'set'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'to'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '"0"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'or'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '"1"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'string'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '#'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: '__LOG_LEVEL__'
```

**Comment by alexAubin** [comment]
Fixed via https://github.com/YunoHost/package_check/commit/aaca7137908169f04b6357bd18a89e2f6add6c41
