### ISSUE TITLE
smtp relay cli configuration fails on yunohost 12.0

### ISSUE THREAD

**Issue by bganne** [YunoHost/issues#2483]
### Describe the bug

When trying to enable SMTP relay via yunohost CLI on a fresh Yunohost 12.0 install, I see the following error:
```sh
root@dmz:/# yunohost settings set email.smtp.smtp_relay_enabled -v yes

========================================
>>>> Email
========================================

# SMTP
Info: Saving the new configuration...
Success! Config updated as expected
root@dmz:/# yunohost settings get email.smtp.smtp_relay_enabled 
1
root@dmz:/# yunohost settings set email.smtp.smtp_relay_host -v mail.example.com

========================================
>>>> Email
========================================

# SMTP
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 77, in <module>
    yunohost.cli(
  File "/usr/lib/python3/dist-packages/yunohost/__init__.py", line 41, in cli
    ret = moulinette.cli(
          ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/__init__.py", line 115, in cli
    ).run(args, output_as=output_as, timeout=timeout)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/cli.py", line 498, in run
    ret = self.actionsmap.process(args, timeout=timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 561, in process
    return func(**arguments)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 483, in func_wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/settings.py", line 102, in settings_set
    return settings.set(key, value, args, args_file, operation_logger=operation_logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 577, in set
    self.form = self._ask(
                ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 868, in _ask
    form = prompt_or_validate_form(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/form.py", line 2063, in prompt_or_validate_form
    if not option.is_visible(context):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/form.py", line 429, in is_visible
    return evaluate_simple_js_expression(self.visible, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/form.py", line 216, in evaluate_simple_js_expression
    return evaluate_simple_ast(node, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/form.py", line 104, in evaluate_simple_ast
    return context[node.id]
           ~~~~~~~^^^^^^^^^
KeyError: 'smtp_relay_enabled'
root@dmz:/#
```

### Context

- Hardware: *LXC container*
- YunoHost version:
```
root@dmz:/# yunohost --version
yunohost: 
  repo: stable
  version: 12.0.7
yunohost-admin: 
  repo: stable
  version: 12.0.3.5
yunohost-portal: 
  repo: stable
  version: 12.0.6
moulinette: 
  repo: stable
  version: 12.0.3
ssowat: 
  repo: stable
  version: 12.0.3
```
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: trying to enable SMTP relay through CLI

### To reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
```sh
yunohost settings set email.smtp.smtp_relay_host -v mail.example.com
```

### Expected behavior

SMTP relay should be configured successfully.

Thanks!

**Comment by bganne** [comment]
I dug a bit deeper into this issue, and it looks like it's related to the fact that the option `smtp.relay_host` is marked with ` visible="smtp_relay_enabled"`in `/usr/share/yunohost/config_global.toml`.
If I remove this, it works just fine.
Looking into the source, I see that in `ConfigPanel._ask()`, `context` is initialized as an empty dict `{}` and then passed as this down the line, until failing in `evaluate_simple_ast()` because there is not such key.
So workaround for now should be to remove `visible=` attributes from `config_global.toml` but I think there is a bug in the way it is handled from CLI.
