### ISSUE TITLE
Config panel broken when `visible` parameter used 

### ISSUE THREAD

**Issue by Josue-T** [YunoHost/issues#2488]
### Describe the bug

Related to https://forum.yunohost.org/t/update-panel-main-of-app-synapse-configuration/32028

It seem that the config panel is broken on bookworm when we use the `visible` parameter which is linked to a settings which is in an other section.

### Context

- Hardware: All
- YunoHost version: 12.0.5.2
- I have access to my server: yes

### To reproduce

- Install synapse (which is impacted by this issue).
- Go on the main tab
- change any value
- save
- And see this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 473, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 561, in process
    return func(**arguments)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/log.py", line 483, in func_wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/app.py", line 1873, in app_config_set
    return config_.set(key, value, args, args_file, operation_logger=operation_logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 577, in set
    self.form = self._ask(
                ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 868, in _ask
    form = prompt_or_validate_form(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/form.py", line 2063, in prompt_or_validate_form
    if not option.is_visible(context):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/form.py", line 429, in is_visible
    return evaluate_simple_js_expression(self.visible, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/form.py", line 216, in evaluate_simple_js_expression
    return evaluate_simple_ast(node, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/utils/form.py", line 104, in evaluate_simple_ast
    return context[node.id]
           ~~~~~~~^^^^^^^^^
KeyError: 'enable_notifs'
```

### Expected behavior

The save should work

### Details

The issue is caused because in synapse the config panel use at some place the `visible` parameter. And in the [`notif_for_new_users` section](https://github.com/YunoHost-Apps/synapse_ynh/blob/master/config_panel.toml#L77) the visible value target the other parameter [`enable_notifs` parameter](https://github.com/YunoHost-Apps/synapse_ynh/blob/master/config_panel.toml#L125C26-L125C39) which is in an other section. Removing the parameter `visible` on line 77 solve the problem so to me this confirm that this is the reason of the issue.

Note it seem to be a regression as it was working on Yunohost 11

**Comment by tokenwizard** [comment]
I'm still getting this as of today on YH version 12.0.10 when trying to Save changes in the Main Settings screen.

**Comment by djelouze** [comment]
Same here, so I can't see public rooms on other servers than matrix.org when I try to fetch the list.

The error show also these information:

```
Erreur: "500"
Action: "PUT" /yunohost/api/apps/synapse/config/main

```

And then follows the exact same message from OP.

**Comment by xhabih** [comment]
Same problem on YH 12.0.11

**Comment by Axolotle** [comment]
Fields's `visible` expressions are evaluated against a context containing previous values of the current section's options as [added in the doc](https://doc.yunohost.org/packaging/advanced/config_panels/#visible--enabled-expression-evaluation) after the last refactoring.

> This quite limited current design exists because on the web-admin or on the CLI we cannot guarantee that a value will be present in the form if the user queried only a single panel/section/option. In the case of an action, the user will be shown or asked for each of the options of the section in which the button is present.

So you should put your option with `visible` in the same section of referenced options.

But it should error out more gracefully, will add proper error handling in https://github.com/YunoHost/yunohost/pull/2005
