### ISSUE TITLE
Can't re-install a multi-instance app with app id instead of url

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#442]
###### Original Redmine Issue: [442](https://dev.yunohost.org/issues/442)

Author Name: **opi**

---

We you install a custom app for the first time, you need to use the Git url, from the web administration (text field on the `/apps/install`) or the command line (`yunohost app install https://path.to/app/repo`).

Then, if this app is defined as multi-instance, you can find it listed in the `/apps/install` page, or you can even try to type `yunohost app install <app-id>`, but both of these methods fail without an explicit error.

Here is some debug trace:

```
22476 INFO     yunohost.app _fetch_app_from_git - [2143.7] Téléchargement...
22484 DEBUG    moulinette.actionsmap process - action [2143.7] ended after 0.010s
22486 DEBUG    moulinette.core release - lock has been released
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 672, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 258, in wrapper
    return callback((request.method, context.rule), params)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 380, in process
    ret = self.actionsmap.process(arguments, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 467, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/app.py", line 463, in app_install
    manifest = _fetch_app_from_git(app)
  File "/usr/lib/moulinette/yunohost/app.py", line 1284, in _fetch_app_from_git
    app_info['manifest']['lastUpdate'] = app_info['lastUpdate']
KeyError: 'lastUpdate'
22501 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2016-06-27 20:39:21] "POST /apps HTTP/1.1" 500 881 0.094021
22503 DEBUG    geventwebsocket.handler close - Closed WebSocket
```

and `yunohost apps list --raw` return for this app, once installed:
```
<my_app_id>: 
  installed: True
  manifest: 
    [...]
  repository: None
  status: 
    installed_at: xxx
    remote: 
      branch: master
      revision: 12345azert123456qsdfg
      type: git
      url: https://github.com/path/to/repository
    upgraded_at: None
```

The error happens in `_fetch_app_from_git`, and maybe this function can take care of the `repository: None` key, but I'm not sure yet.

**Comment by alexAubin** [comment]
Closing, I would guess that's fixed by now
