### ISSUE TITLE
Uncaught exception because of missing lastUpdate field in app info ?

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#686]
###### Original Redmine Issue: [686](https://dev.yunohost.org/issues/686)

Author Name: **alexAubin**

---

Trying to install rainloop (which was actually already installed) :

```
 > yunohost app install rainloop
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 217, in <module>
    timeout=opts.timeout,
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 138, in cli
    moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 353, in run
    ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 479, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/app.py", line 467, in app_install
    manifest, extracted_app_folder = _fetch_app_from_git(app)
  File "/usr/lib/moulinette/yunohost/app.py", line 1301, in _fetch_app_from_git
    app_info['manifest']['lastUpdate'] = app_info['lastUpdate']
KeyError: 'lastUpdate'
```

I'm guessing this is because https://raw.githubusercontent.com/polytan02/rainloop_ynh/master/manifest.json doesn't have the "lastUpdate" entry ?

**Comment by alexAubin** [comment]
Closing because this is probably fixed since then .. app_info etc. got refactored multiple time since 2018
