### ISSUE TITLE
Be able to override hooks

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#886]
###### Original Redmine Issue: [886](https://dev.yunohost.org/issues/886)

Author Name: **ljf**

---

Currently, we can add custom hooks, but we can't overwrite a hook.

If we try there is an error like that

~~~ diff
2017-04-03 08:32:57,518 WARNING  yunohost.hook <lambda> - [3844.1] Traceback (most recent call last):
2017-04-03 08:32:57,520 WARNING  yunohost.hook <lambda> - [3844.1]   File "/usr/bin/yunohost", line 217, in <module>
2017-04-03 08:32:57,522 WARNING  yunohost.hook <lambda> - [3844.1]     timeout=opts.timeout,
2017-04-03 08:32:57,524 WARNING  yunohost.hook <lambda> - [3844.1]   File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 139, in cli
2017-04-03 08:32:57,531 WARNING  yunohost.hook <lambda> - [3844.1]     moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
2017-04-03 08:32:57,533 WARNING  yunohost.hook <lambda> - [3844.1]   File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 358, in run
2017-04-03 08:32:57,538 WARNING  yunohost.hook <lambda> - [3844.1]     ret = self.actionsmap.process(args, timeout=timeout)
2017-04-03 08:32:57,539 WARNING  yunohost.hook <lambda> - [3844.1]   File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 484, in process
2017-04-03 08:32:57,543 WARNING  yunohost.hook <lambda> - [3844.1]     return func(**arguments)
2017-04-03 08:32:57,544 WARNING  yunohost.hook <lambda> - [3844.1]   File "/usr/lib/moulinette/yunohost/service.py", line 326, in service_regen_conf
2017-04-03 08:32:57,546 WARNING  yunohost.hook <lambda> - [3844.1]     pre_result = hook_callback('conf_regen', names, pre_callback=_pre_call)
2017-04-03 08:32:57,546 WARNING  yunohost.hook <lambda> - [3844.1]   File "/usr/lib/moulinette/yunohost/hook.py", line 276, in hook_callback
2017-04-03 08:32:57,549 WARNING  yunohost.hook <lambda> - [3844.1]     path=path, args=args)
2017-04-03 08:32:57,550 WARNING  yunohost.hook <lambda> - [3844.1]   File "/usr/lib/moulinette/yunohost/service.py", line 323, in _pre_call
2017-04-03 08:32:57,551 WARNING  yunohost.hook <lambda> - [3844.1]     filesystem.mkdir(service_pending_path, 0755, True, uid='admin')
2017-04-03 08:32:57,552 WARNING  yunohost.hook <lambda> - [3844.1]   File "/usr/lib/python2.7/dist-packages/moulinette/utils/filesystem.py", line 28, in mkdir
2017-04-03 08:32:57,566 WARNING  yunohost.hook <lambda> - [3844.1]     raise OSError(errno.EEXIST, m18n.g('folder_exists', path=path))
2017-04-03 08:32:57,567 WARNING  yunohost.hook <lambda> - [3844.1] OSError: [Errno 17] Folder already exists: '/home/yunohost.conf/pending/postfix_sympa'
~~~
Inb this example postfix_sympa hook was in /etc/yunohost/hooks.d/conf_regen/ and in /usr/share/yunohost/hooks/conf_regen/

**Comment by alexAubin** [comment]
Hmmmm do we really want to allow this @.@ ...

**Comment by alexAubin** [comment]
I dunno how this bug was triggered but in the end I was able to implement this kind of hook in sympa / mailman and similarly yalh rencently did it
