### ISSUE TITLE
Certificate install/renew mistakenly thinks domain is not properly resolved locally

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#925]
###### Original Redmine Issue: [925](https://dev.yunohost.org/issues/925)

Author Name: **moul**

---

```bash
yunohost domain cert-renew moul.re --verbose --force
Now attempting renewing of certificate for domain moul.re !
Fehler: Certificate renewing for moul.re failed !
Fehler: Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/certificate.py", line 380, in certificate_renew
    _check_domain_is_ready_for_ACME(domain)
  File "/usr/lib/moulinette/yunohost/certificate.py", line 826, in _check_domain_is_ready_for_ACME
    'certmanager_domain_not_resolved_locally', domain=domain))
MoulinetteError: [Errno 22] Die Domain moul.re konnte von innerhalb des Yunohost-Servers nicht aufgelöst werden. Das kann passieren, wenn du den DNS Eintrag vor Kurzem verändert hast. Falls dies der Fall ist, warte bitte ein paar Stunden, damit die Änderungen wirksam werden. Wenn der Fehler bestehen bleibt, ziehe in Betracht die Domain moul.re in /etc/hosts einzutragen. (Wenn du weißt was du tust, benutze --no-checks , um diese Nachricht zu umgehen. )

Fehler: [Errno 22] Die Domain moul.re konnte von innerhalb des Yunohost-Servers nicht aufgelöst werden. Das kann passieren, wenn du den DNS Eintrag vor Kurzem verändert hast. Falls dies der Fall ist, warte bitte ein paar Stunden, damit die Änderungen wirksam werden. Wenn der Fehler bestehen bleibt, ziehe in Betracht die Domain moul.re in /etc/hosts einzutragen. (Wenn du weißt was du tust, benutze --no-checks , um diese Nachricht zu umgehen. )
```

```bash
>>> import socket
>>> ip = socket.gethostbyname("moul.re")
>>> print ip
192.168.1.14
```

[This check](https://github.com/YunoHost/yunohost/blob/unstable/src/yunohost/certificate.py#L864) fail.

I finally changed `==` to `!=` on this line `return ip.startswith("127.") or ip == public_ip` and `cert-renew` worked.

That strange as renewal worked for `duniter.moul.re` certificate.

**Comment by Psycojoker** [comment]
@alexAubin is it still the case? I remember that I've added code to display debug information on failure.

**Comment by alexAubin** [comment]
I dunno .. Maybe some tweaks that were done (refreshing dnsmasq conf) might have fix this but that's not clear how to reproduce the issue and know what's happening exactly ... Anyway I see a lot less issues related to that kind of stuff on the forum these days, so I would say let's assume that it's fixed :+1:

**Comment by Psycojoker** [comment]
Ok, let's reopen if needed.
